/* Independent reading interface. Text data attribution: see LICENSE-data.txt and README.md. */
'use strict';
const $=s=>document.querySelector(s), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toSimple=OpenCC.Converter({from:'t',to:'cn'});
const KEY='tongjian-reader-v1';let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{saved={}}
const state={books:[],book:'epub2',chapter:4,segment:1,paragraph:0,bookmarks:saved.bookmarks||{},notes:saved.notes||{},last:saved.last||{},seconds:saved.seconds||0,visited:saved.visited||{},tags:saved.tags||{},settings:{size:20,line:2,font:'serif',theme:'light',translation:true,parallel:false,notes:true,annotations:false,simplified:false,...saved.settings}};
let segments=[],loadId=0,observer,searchId=0,worker,totalResults=[],shown=0,searchTerm='';
const fonts={serif:'"Songti SC","SimSun",serif',kai:'"Kaiti SC","STKaiti",serif',sans:'"PingFang SC","Microsoft YaHei",sans-serif'};
const terms={诸侯:'古代分封制度下拥有封国的统治者。周代诸侯在名义上服从周天子，爵位有公、侯、伯、子、男。',卿:'古代高级官员的称谓。在周代的政治等级中，卿位于诸侯之下、大夫之上。',大夫:'古代官职和身份等级，位于卿之下、士之上。晋国后期的大夫家族逐渐控制国政。',智伯:'智瑶，晋国智氏宗主。与韩、魏联合围攻赵氏，后被三家反攻，智氏覆灭。',三家分晋:'韩、赵、魏三家分割晋国。公元前403年，周威烈王正式册封三家为诸侯，《资治通鉴》以此开篇。',晋阳:'古代城邑，位于今山西太原一带。晋阳之战中，赵襄子据此抵抗智伯。',礼:'在古代政治语境中，不只指礼仪，也包括维护社会秩序、等级和名分的制度与规范。',司马光:'司马光（1019—1086），北宋政治家、史学家，主持编纂《资治通鉴》。',胡三省:'胡三省（1230—1302），宋元之际史学家，著有《资治通鉴音注》，重视地理、制度及史事考证。'};
function persist(){try{localStorage.setItem(KEY,JSON.stringify({bookmarks:state.bookmarks,notes:state.notes,last:state.last,seconds:state.seconds,visited:state.visited,tags:state.tags,settings:state.settings}))}catch{toast('保存失败，浏览器存储空间不足。')}}
function toast(t){$('#toast').textContent=t;$('#toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.opacity=0,2300)}
function applySettings(){let s=state.settings;document.body.dataset.theme=s.theme;document.documentElement.style.setProperty('--size',s.size+'px');document.documentElement.style.setProperty('--line',s.line);document.documentElement.style.setProperty('--font',fonts[s.font]||fonts.serif)}
function book(){return state.books.find(b=>b.id===state.book)}
function key(p=state.paragraph){return `${state.book}:${state.chapter}:${state.segment}:${p}`}
function readingLocation(p=state.paragraph){return {book:state.book,chapter:state.chapter,segment:state.segment,paragraph:p,title:segments[state.segment]?.title||book().chapters[state.chapter].title,date:Date.now()}}
function openDialog(title,html){$('#dialog').classList.remove('person-dialog','settings-dialog');$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog').scrollTop=0;if(!$('#dialog').open)$('#dialog').showModal()}
$('#close-dialog').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){let r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
function renderBooks(){$('#books').innerHTML=state.books.filter(b=>b.id!=='tongjian').map(b=>`<button data-book="${b.id}" class="${(b.id===state.book||(b.id==='epub2'&&state.book==='tongjian'))?'active':''}" aria-pressed="${b.id===state.book||(b.id==='epub2'&&state.book==='tongjian')}">${E(b.title.replace('通鉴纪事本末','纪事本末'))}</button>`).join('');$('#author').textContent=book().author}
function renderTree(){const q=$('#toc-filter').value.trim();$('#tree').innerHTML=book().chapters.map((c,i)=>{let match=c.title.includes(q)||c.segments.some(t=>t.includes(q));if(q&&!match)return '';return `<details class="${i===state.chapter?'current':''}" ${i===state.chapter||q?'open':''}><summary>${E(c.title)}</summary>${c.segments.map((t,j)=>q&&!c.title.includes(q)&&!t.includes(q)?'':`<button class="year ${i===state.chapter&&j===state.segment?'active':''}" data-chapter="${i}" data-segment="${j}">${E(t)}</button>`).join('')}</details>`}).join('')||'<p class="empty">没有匹配的卷目</p>'}
$('#toc-filter').oninput=renderTree;
async function navigate(b,c=0,s=0,p=0,updateHash=true){const id=++loadId;state.book=b;state.chapter=Math.max(0,Math.min(c,book().chapters.length-1));state.segment=s;state.paragraph=p;renderBooks();renderTree();$('#content').innerHTML='<p class="muted">正在载入正文…</p>';try{const r=await fetch(`data/${state.book}-${state.chapter}.json?v=people-audit2`);if(!r.ok)throw Error();const data=await r.json();if(id!==loadId)return;segments=data;state.segment=Math.max(0,Math.min(s,data.length-1));state.paragraph=Math.max(0,Math.min(p,data[state.segment].paragraphs.length-1));renderTree();renderContent();state.last[b]=readingLocation();state.visited[`${b}:${state.chapter}:${state.segment}`]=true;persist();if(updateHash)history.pushState(null,'',`#${key()}`);document.body.classList.remove('mobile-toc');$('#reading').scrollTop=0;if(state.paragraph)jumpTo(state.paragraph);else $('#reading').focus({preventScroll:true});}catch{if(id!==loadId)return;$('#content').innerHTML='<p>正文载入失败，请检查连接后重试。</p><button class="primary" id="retry">重试</button>';$('#retry').onclick=()=>navigate(b,c,s,p)}}
function displayText(t){return E(state.settings.simplified?toSimple(t):t)}
function noteHTML(t){return t.parts?t.parts.map(p=>p.src?`<img class="original-glyph" src="${E(p.src)}" alt="原书异体字形">`:displayText(p.text)).join(''):displayText(t.text)}
function renderOriginal(r){return r.tokens?r.tokens.map(t=>t.kind==='image'?`<img class="original-glyph" src="${E(t.src)}" alt="原书异体字形">`:t.note?(state.settings.annotations?`<span class="annotation-inline">〔${noteHTML(t)}〕</span>`:`<span class="annotation-label">〔注〕</span>`):t.kind==='name'&&t.personMention!==undefined?`<button class="entity-name person-name" data-person="${t.personMention}" aria-label="查看人物 ${E(t.text)}">${displayText(t.text)}</button>`:`<span class="entity-${E(t.kind||'text')}">${displayText(t.text)}</span>`).join(''):displayText(r.o)}
function renderContent(){const seg=segments[state.segment],cfg=state.settings;$('#path').textContent=`${book().title} / ${book().chapters[state.chapter].title} / ${seg.title}`;$('#content').innerHTML=`<h1>${E(seg.title)}</h1>${book().chapters[state.chapter].warning?`<p class="search-status">${E(book().chapters[state.chapter].warning)}</p>`:''}${seg.headingNote?`<details class="heading-note"><summary>纪年注释</summary><p>${E(seg.headingNote)}</p></details>`:''}<div class="chapter-title">${E(book().chapters[state.chapter].title)} · ${seg.paragraphs.length} 段</div>`+seg.paragraphs.map((r,i)=>{let k=key(i),note=state.notes[k];return `<section class="paragraph" id="p-${i}" data-p="${i}"><div class="separator">${i+1} / ${seg.paragraphs.length}</div><div class="paragraph-actions"><button data-save="${i}" aria-label="${state.bookmarks[k]?'取消段落收藏':'收藏段落'}" class="${state.bookmarks[k]?'saved':''}">${state.bookmarks[k]?'★':'☆'} 收藏</button><button data-note="${i}">✎ ${note?'编辑批注':'写批注'}</button><button data-detail="${i}">${r.annotations?.length?'胡注 '+r.annotations.length+' 条':'释义'}</button><button data-copy="${i}" aria-label="复制段落链接">链接</button>${i===0&&state.book==='tongjian'&&state.chapter===0?'<span class="tag">三家分晋</span>':''}</div><div class="texts ${cfg.parallel&&cfg.translation&&r.t?'parallel':''}"><p class="original" tabindex="0" role="group" aria-label="第${i+1}段，查看释义与批注" data-detail="${i}">${renderOriginal(r)}</p>${cfg.translation&&r.t?`<p class="translated"><small class="translation-label">白话译文</small>${E(r.t)}</p>`:cfg.translation&&r.translationStatus==='missing'?'<p class="translation-missing">译文待补</p>':''}</div>${note&&cfg.notes?`<div class="note-inline"><strong>我的批注</strong><br>${E(note.text)}</div>`:''}</section>`}).join('');updateBookmark();$('#counter').textContent=book().chapters[state.chapter].title;$('#prev').disabled=state.chapter===0&&state.segment===0;$('#next').disabled=state.chapter===book().chapters.length-1&&state.segment===segments.length-1;
observer?.disconnect();observer=new IntersectionObserver(es=>{for(let e of es)if(e.isIntersecting){state.paragraph=Number(e.target.dataset.p);state.last[state.book]=readingLocation();persist();}},{root:$('#reading'),rootMargin:'-10% 0px -70% 0px',threshold:0});document.querySelectorAll('.paragraph').forEach(e=>observer.observe(e));}
function jumpTo(p){requestAnimationFrame(()=>{let target=$('#p-'+p);if(target){$('#reading').scrollTop=target.offsetTop-$('#reading').offsetTop-20;target.classList.add('highlight');setTimeout(()=>target.classList.remove('highlight'),1800)}})}
function updateBookmark(){let exists=state.bookmarks[`${state.book}:${state.chapter}:${state.segment}:chapter`];$('#bookmark').textContent=exists?'★':'☆';$('#bookmark').setAttribute('aria-label',exists?'取消章节书签':'添加章节书签')}
function toggleSave(p,chapter=false){let k=chapter?`${state.book}:${state.chapter}:${state.segment}:chapter`:key(p);if(state.bookmarks[k]){delete state.bookmarks[k];toast('已取消收藏')}else{state.bookmarks[k]={...readingLocation(p),type:chapter?'chapter':'paragraph',excerpt:chapter?'':segments[state.segment].paragraphs[p].o.slice(0,95)};toast('已保存书签')}persist();let scroll=$('#reading').scrollTop;renderContent();$('#reading').scrollTop=scroll}
function paragraphDialog(p){const r=segments[state.segment].paragraphs[p],note=state.notes[key(p)];const selection=captureReadingQuote(r.o);openDialog('段落释义与批注',`<p class="search-status">${E(segments[state.segment].title)} · 第 ${p+1} 段</p><blockquote>${E(r.o)}</blockquote>${r.t?`<h3>白话文</h3><p style="line-height:2">${E(r.t)}</p><p class="search-status">文白参考译文 · JY0284/zizhitongjian</p>`:r.translationStatus==='missing'?'<p class="search-status">本段译文待补</p>':''}${r.annotations?.length?`<h3>胡三省注与校注</h3>${r.annotations.map((n,j)=>`<p class="annotation-full"><small>${j+1}</small> ${r.tokens?.filter(t=>t.note)[j]?noteHTML(r.tokens.filter(t=>t.note)[j]):displayText(n)}</p>`).join('')}`:''}<h3>词语释义</h3><div class="glossary">${Object.keys(terms).filter(t=>toSimple(r.o).includes(t)).map(t=>`<button data-term="${E(t)}">${E(t)}</button>`).join('')||'<span class="muted">本段暂无内置词语释义</span>'}</div><h3>我的批注</h3>${selection&&r.o.includes(selection)?`<p class="search-status">选中文字：${E(selection)}</p>`:''}<textarea id="note-text" placeholder="写下你的理解、疑问或联想…" aria-label="批注内容">${E(note?.text||'')}</textarea><div class="row"><button class="primary" id="save-note">保存批注</button>${note?'<button id="remove-note">删除批注</button>':''}<span class="search-status">保存在当前浏览器</span></div>`);$('#save-note').onclick=()=>{const text=$('#note-text').value.trim();if(!text){toast('请填写批注内容');return}state.notes[key(p)]={...readingLocation(p),text,quote:selection&&r.o.includes(selection)?selection:note?.quote||'',excerpt:r.o.slice(0,95)};persist();let pos=$('#reading').scrollTop;renderContent();$('#reading').scrollTop=pos;$('#dialog').close();toast('批注已保存')};if(note)$('#remove-note').onclick=()=>{delete state.notes[key(p)];persist();let pos=$('#reading').scrollTop;renderContent();$('#reading').scrollTop=pos;$('#dialog').close();toast('批注已删除')};}
function collection(type){let isNotes=type==='notes',rows=Object.entries(isNotes?state.notes:state.bookmarks).sort((a,b)=>b[1].date-a[1].date);openDialog(isNotes?'我的批注':'书签与收藏',rows.length?rows.map(([k,r])=>`<div class="row" style="border-bottom:1px solid var(--border);align-items:flex-start"><button class="result" style="flex:1;border:0" data-location="${E(JSON.stringify(r))}"><strong>${E(state.books.find(b=>b.id===r.book)?.title)} / ${E(r.title)}</strong><p>${E(isNotes?r.text:r.excerpt||'章节书签')}</p>${isNotes?`<small>${E(r.excerpt)}</small>`:''}</button><button data-delete="${E(k)}" data-type="${type}" aria-label="删除${isNotes?'批注':'收藏'}">删除</button></div>`).join(''):`<p class="empty">还没有${isNotes?'批注':'书签'}。<br>${isNotes?'点击段落上的“写批注”。':'点击章节或段落旁的星标即可收藏。'}</p>`)}
function settingsDialog(){let s=state.settings;openDialog('阅读配置',`<div class="setting"><label for="edition">资治通鉴版本</label><select id="edition"><option value="epub2" ${state.book!=='tongjian'?'selected':''}>你提供的 EPUB · 繁体胡注本</option><option value="tongjian" ${state.book==='tongjian'?'selected':''}>文白对照本 · 简体</option></select></div><div class="setting"><label for="size">字体大小 <output id="size-out">${s.size}px</output></label><input id="size" type="range" min="16" max="36" value="${s.size}" data-setting="size"></div><div class="setting"><label for="line">行间距 <output id="line-out">${s.line}</output></label><input id="line" type="range" min="1.5" max="3" step="0.1" value="${s.line}" data-setting="line"></div><div class="setting"><label for="font">正文字体</label><select id="font" data-setting="font">${Object.entries({serif:'宋体',kai:'楷体',sans:'黑体'}).map(([v,l])=>`<option value="${v}" ${s.font===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="setting"><label for="theme">背景模式</label><select id="theme" data-setting="theme">${Object.entries({light:'正常',eye:'护眼',dark:'夜间'}).map(([v,l])=>`<option value="${v}" ${s.theme===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="row"><label><input type="checkbox" data-setting="simplified" ${s.simplified?'checked':''}> 显示简体</label><label><input type="checkbox" data-setting="annotations" ${s.annotations?'checked':''}> 展开胡三省注与校注</label><label><input type="checkbox" data-setting="translation" ${s.translation?'checked':''}> 显示白话文</label><label><input type="checkbox" data-setting="parallel" ${s.parallel?'checked':''}> 文白左右对照</label><label><input type="checkbox" data-setting="notes" ${s.notes?'checked':''}> 展开我的批注</label></div><p class="search-status">宽屏支持左右对照，窄屏自动上下排列。字体使用设备中已安装的字体。你提供的胡注本已接入正文白话参考译文，译文显示在原文下方；开启左右对照可并排阅读。未配到译文的段落会标明“译文待补”。胡三省注、序跋、附录、纪事本末和读通鉴论保留原文。</p><button id="reset-settings">恢复默认设置</button>`);$('#edition').onchange=()=>{let b=$('#edition').value;let r=state.last[b]||{chapter:b==='epub2'?4:0,segment:b==='epub2'?1:0,paragraph:0};$('#dialog').close();navigate(b,r.chapter,r.segment,r.paragraph)};$('#dialog-body').querySelectorAll('[data-setting]').forEach(el=>el.oninput=()=>{let name=el.dataset.setting;state.settings[name]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;if(name==='size')$('#size-out').textContent=el.value+'px';if(name==='line')$('#line-out').textContent=el.value;applySettings();let pos=$('#reading').scrollTop;renderContent();$('#reading').scrollTop=pos;persist()});$('#reset-settings').onclick=()=>{state.settings={size:20,line:2,font:'serif',theme:'light',translation:true,parallel:false,notes:true,annotations:false,simplified:false};applySettings();renderContent();persist();settingsDialog()}}
function spaceDialog(){openDialog('个人空间',`<div class="row"><div><div class="stat">${Math.floor(state.seconds/60)}</div>阅读分钟</div><div style="margin-left:30px"><div class="stat">${Object.keys(state.visited).length}</div>已读章节</div><div style="margin-left:30px"><div class="stat">${Object.keys(state.notes).length}</div>个人批注</div></div><h3>继续阅读</h3>${Object.values(state.last).sort((a,b)=>b.date-a.date).map(r=>`<button class="result" data-location="${E(JSON.stringify(r))}"><strong>${E(state.books.find(b=>b.id===r.book)?.title)}</strong><p>${E(r.title)} · 第 ${r.paragraph+1} 段</p></button>`).join('')||'<p class="empty">开始阅读后，会在这里记录进度。</p>'}<p class="search-status">阅读记录保存在当前浏览器，关闭页面后仍会保留。清除浏览器网站数据会删除这些记录。</p>`)}
function glossary(t){openDialog(t,`<p style="font-size:17px;line-height:2">${E(terms[t])}</p><button class="primary" id="find-term">搜索相关段落</button>`);$('#find-term').onclick=()=>searchDialog(t)}
function searchDialog(q=''){openDialog('搜索与百科',`<form class="search-form" id="search-form"><select id="search-book" aria-label="搜索范围"><option value="all">全部书籍</option>${state.books.map(b=>`<option value="${b.id}" ${b.id===state.book?'selected':''}>${E(b.title)}</option>`).join('')}</select><input id="search-query" placeholder="输入人物、词语或年份（繁简均可）" aria-label="搜索词" value="${E(q)}" required><button class="primary">搜索</button></form><div class="row"><label><input type="radio" name="match" value="fuzzy" checked> 模糊搜索</label><label><input type="radio" name="match" value="exact"> 精准搜索</label><label><input type="checkbox" id="translations" checked> 包含白话文</label></div><p id="search-status" class="search-status">输入关键词搜索全文。多个词用空格分隔。</p><div id="results"></div><div id="more"></div>`);$('#search-form').onsubmit=e=>{e.preventDefault();runSearch()};if(q)runSearch();else $('#search-query').focus()}
function runSearch(){const q=$('#search-query').value.trim();if(!q)return;searchTerm=q;$('#search-status').textContent='正在搜索全文，首次搜索需加载文本索引…';$('#results').innerHTML='';$('#more').innerHTML='';if(!worker){worker=new Worker('search-worker.js?v=people-audit2');worker.onmessage=e=>{if(e.data.id!==searchId||!$('#results'))return;if(e.data.error){$('#search-status').textContent='搜索索引载入失败，请重试。';return}totalResults=e.data.results;shown=0;$('#search-status').textContent=`共找到 ${e.data.total} 个匹配段落${e.data.total>600?'，显示前 600 个，请缩小搜索范围。':'。'}`;if(!totalResults.length)$('#results').innerHTML='<p class="empty">没有找到匹配段落，试试人物名或更短的关键词。</p>';showMore()};worker.onerror=()=>{if($('#search-status'))$('#search-status').textContent='搜索暂时不可用，请刷新后重试。'}}worker.postMessage({id:++searchId,q,book:$('#search-book').value,exact:$('input[name=match]:checked').value==='exact',translated:$('#translations').checked})}
function highlight(text){const norm=toSimple(text),words=searchTerm.split(/\s+/).filter(Boolean).map(toSimple);let marked=new Set();for(let word of words){let at=norm.indexOf(word);while(at>=0){for(let i=at;i<at+word.length;i++)marked.add(i);at=norm.indexOf(word,at+Math.max(1,word.length))}}let out='',on=false;for(let i=0;i<text.length;i++){let selected=marked.has(i);if(selected&&!on)out+='<mark>';if(!selected&&on)out+='</mark>';out+=E(text[i]);on=selected}return out+(on?'</mark>':'')}
function showMore(){let slice=totalResults.slice(shown,shown+30);$('#results').insertAdjacentHTML('beforeend',slice.map(r=>{let [b,c,s,p,t,o,tr]=r;let terms=searchTerm.split(/\s+/).map(toSimple);let text=terms.some(w=>toSimple(o).includes(w))?o:tr||o;let idx=Math.max(0,...terms.map(w=>toSimple(text).indexOf(w)));let start=Math.max(0,idx-45);let preview=(start?'…':'')+text.slice(start,start+180)+(text.length>start+180?'…':'');return `<button class="result" data-location="${E(JSON.stringify({book:b,chapter:c,segment:s,paragraph:p}))}"><strong>${E(state.books.find(x=>x.id===b)?.title)} · ${E(state.books.find(x=>x.id===b)?.chapters[c].title)} · ${E(t)}</strong><p>${highlight(preview)}</p><small>第 ${p+1} 段 · 点击回到正文</small></button>`}).join(''));shown+=slice.length;$('#more').innerHTML=shown<totalResults.length?'<button id="more-results" class="primary" style="margin-top:20px">加载更多结果</button>':'';if($('#more-results'))$('#more-results').onclick=showMore}
const actions={search:()=>searchDialog(),settings:settingsDialog,space:spaceDialog,bookmark:()=>toggleSave(0,true),bookmarks:()=>collection('bookmarks'),notes:()=>collection('notes'),nav:()=>{if(innerWidth<=680)document.body.classList.toggle('mobile-toc');else document.body.classList.toggle('hide-toc')},aside:()=>{if(innerWidth<=1100)document.body.classList.toggle('show-tools');else document.body.classList.toggle('hide-tools')},about:()=>openDialog('版本与文本来源','<p>这是参考读通鉴阅读布局制作的独立阅读版。</p><p>主版本来自你指定的《資治通鑑.epub》，保留繁体、胡三省注与原书校注；301 个目录项，包括 294 卷及序跋、附录。已替换此前的 EPUB。主版本仅用于本地阅读。</p><p>《资治通鉴》文白对照：<a href="https://github.com/JY0284/zizhitongjian" target="_blank" rel="noreferrer">JY0284/zizhitongjian</a>，294 卷，依原数据保留段落。数据按 GPL-3.0 许可分发，见 <a href="LICENSE-data.txt">数据许可</a>。</p><p>《通鉴纪事本末》《读通鉴论》原文：<a href="https://github.com/lhw828/GuWen" target="_blank" rel="noreferrer">GuWen 古籍整理库</a>。词语释义为本版编写的基础阅读说明。</p><p>历史地图、气候和补充阅读资料已接入；沙盘态势支持地图标绘和推演记录；AI、账号同步留待后续接入。</p>')};
document.addEventListener('click',e=>{const person=e.target.closest('[data-person]');if(person){e.preventDefault();personDialog(Number(person.dataset.person));return}const el=e.target.closest('button,[data-detail]');if(!el)return;if(el.dataset.action){actions[el.dataset.action]?.();return}if(el.dataset.book){const r=state.last[el.dataset.book];$('#toc-filter').value='';navigate(el.dataset.book,r?.chapter??(el.dataset.book==='epub2'?4:0),r?.segment??(el.dataset.book==='epub2'?1:0),r?.paragraph||0);return}if(el.dataset.chapter!==undefined){navigate(state.book,+el.dataset.chapter,+el.dataset.segment);return}if(el.dataset.save!==undefined){toggleSave(+el.dataset.save);return}if(el.dataset.note!==undefined){paragraphDialog(+el.dataset.note);$('#note-text').focus();return}if(el.dataset.detail!==undefined){if(el.matches('.original')&&state.settings.clickLink){translationDialog(+el.dataset.detail)}else paragraphDialog(+el.dataset.detail);return}if(el.dataset.location){let r=JSON.parse(el.dataset.location);$('#dialog').close();navigate(r.book,r.chapter,r.segment,r.paragraph||0);return}if(el.dataset.delete){delete state[el.dataset.type==='notes'?'notes':'bookmarks'][el.dataset.delete];persist();collection(el.dataset.type);let pos=$('#reading').scrollTop;renderContent();$('#reading').scrollTop=pos;return}if(el.dataset.term){glossary(el.dataset.term);return}if(el.dataset.copy!==undefined){let url=new URL(location.href);url.hash=key(+el.dataset.copy);navigator.clipboard?.writeText(url.href).then(()=>toast('段落链接已复制')).catch(()=>openDialog('段落链接',`<input value="${E(url.href)}" aria-label="段落链接" style="width:100%" readonly>`));}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('.original'))(state.settings.clickLink?translationDialog:paragraphDialog)(+e.target.dataset.detail);if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();searchDialog()}});
$('#quick-form').onsubmit=e=>{e.preventDefault();searchDialog($('#quick-search').value.trim())};
$('#prev').onclick=()=>state.segment>0?navigate(state.book,state.chapter,state.segment-1):navigate(state.book,state.chapter-1,book().chapters[state.chapter-1].segments.length-1);
$('#next').onclick=()=>state.segment<segments.length-1?navigate(state.book,state.chapter,state.segment+1):navigate(state.book,state.chapter+1);
function parseHash(){let [b,c,s,p]=location.hash.slice(1).split(':');if(!state.books.some(x=>x.id===b))return null;return {book:b,chapter:Number(c)||0,segment:Number(s)||0,paragraph:Number(p)||0}}
window.addEventListener('popstate',()=>{$('#dialog').close();let r=parseHash();if(r)navigate(r.book,r.chapter,r.segment,r.paragraph,false)});
let lastTick=Date.now();setInterval(()=>{let now=Date.now(),delta=(now-lastTick)/1000;lastTick=now;if(!document.hidden&&delta<10&&!$('#dialog').open){state.seconds+=delta;$('#time').textContent=`已读 ${Math.floor(state.seconds/60)} 分`;persist()}},5000);
applySettings();$('#time').textContent=`已读 ${Math.floor(state.seconds/60)} 分`;$('#glossary').innerHTML=Object.keys(terms).map(t=>`<button data-term="${E(t)}">${E(t)}</button>`).join('');
(async()=>{try{const r=await fetch('data/catalog.json');if(!r.ok)throw Error();state.books=await r.json();let initial=parseHash()||state.last.epub2||{book:'epub2',chapter:4,segment:1,paragraph:0};await navigate(initial.book,initial.chapter,initial.segment,initial.paragraph,false)}catch{$('#content').innerHTML='<h1>文本目录载入失败</h1><p>请刷新页面重试。</p>'}})();
