/* Person identities and unresolved mentions are deliberately separate. */
let peoplePromise,peopleRequest=0;
const peopleChapters=new Map();
function peopleIndex(){return peoplePromise??=fetch('data/people/index.json?v=shorthand1').then(r=>{if(!r.ok)throw Error();return r.json()}).catch(e=>{peoplePromise=null;throw e})}
function peopleChapter(c){if(!peopleChapters.has(c))peopleChapters.set(c,fetch(`data/epub2-${c}.json?v=shorthand1`).then(r=>{if(!r.ok)throw Error();return r.json()}).catch(e=>{peopleChapters.delete(c);throw e}));return peopleChapters.get(c)}
function personYear(y){return y==null?'纪年未定':y<0?`前${-y}年`:`${y}年`}
function personLife(p){if(p.lifespanUncertain)return '生卒记载待核';return (p.birthText||(p.birth!=null?personYear(p.birth):'生年不详'))+'—'+(p.deathText||(p.death!=null?personYear(p.death):'卒年不详'))}
function personExcerpt(text,names){const sorted=[...new Set(names)].filter(Boolean).sort((a,b)=>b.length-a.length);if(!sorted.length)return E(text);const re=new RegExp(sorted.map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'g');let end=0,out='';for(const m of text.matchAll(re)){out+=E(text.slice(end,m.index))+`<mark>${E(m[0])}</mark>`;end=m.index+m[0].length;}return out+E(text.slice(end))}
async function personDialog(mentionId,selectedIdentity=null,page=null){
 const request=++peopleRequest;
 openDialog('人物与相关段落','<p class="search-status">正在载入人物资料…</p>');$('#dialog').classList.add('person-dialog');
 try{
  const data=await peopleIndex();let mention=data.occurrences[mentionId];if(!mention)throw Error();if(mention.contextAnchor!==undefined)mention=data.occurrences[mention.contextAnchor];
  const identity=selectedIdentity||mention.who,profile=data.profiles.find(p=>p.id===identity);
  const candidates=mention.n.length>1?data.profiles.filter(p=>p.aliases.includes(mention.n)&&(mention.y==null||(p.birth==null||mention.y>=p.birth)&&mention.y<=p.death)):[];
  const intro=profile;
  let ids=profile?(data.byPerson[profile.id]||[]):(data.byName[mention.n]||[]);
  let rows=ids.map(id=>data.occurrences[id]);const anchor=rows.findIndex(r=>r.c===mention.c&&r.s===mention.s&&r.p===mention.p);
  const size=6,pages=Math.max(1,Math.ceil(rows.length/size)),pg=Math.min(pages-1,Math.max(0,page??Math.floor(Math.max(0,anchor)/size))),visible=rows.slice(pg*size,(pg+1)*size);
  const chapters=await Promise.all(visible.map(r=>peopleChapter(r.c))),context=await peopleChapter(mention.c);
  if(request!==peopleRequest||!$('#dialog').open||!$('#dialog').classList.contains('person-dialog'))return;
  const current=context[mention.s].paragraphs[mention.p],clueAt=Math.max(0,toSimple(context[mention.s].paragraphs[mention.p].o).indexOf(mention.n)),clueStart=Math.max(0,clueAt-50),name=profile?.name||mention.n,alternatives=data.profiles.filter(p=>p.id!==profile?.id&&p.aliases.some(a=>a===mention.n||a===profile?.name));
  const heading=profile?`${name} · ${profile.era}`:`${name} · 身份待辨认`;
  $('#dialog-title').textContent=heading;
  $('#dialog-body').innerHTML=`<div class="person-intro"><strong>${E(name)}</strong> <span>${intro?E(intro.era)+' · '+personLife(intro)+(profile?'':' · 简介候选'):personYear(mention.y)+' · '+E(state.books.find(b=>b.id==='epub2').chapters[mention.c].title)}</span><p>${intro?E(intro.bio)+(profile?'':'（本段身份尚未确认，下方同名段落未合并为此人。）'):'此处尚未建立人物档案。下面提供本段身份线索和前后同名段落，供对照辨认。'}</p>${intro?`<a href="${E(intro.url)}" target="_blank" rel="noopener noreferrer">查看人物资料来源 ↗</a>`:''}</div><div class="person-layout"><aside class="person-facts"><h3>人物资料</h3><p class="identity-status">${profile?(profile.reviewed?'已整理人物档案':'公开人物资料 · 按纪年关联'):'当前记录：本段人名出现'}</p><p class="search-status">${profile?'段落按全名、纪年及同段明确简称关联；仅显示这一人物档案的记录。':'同名段落是检索线索，尚未确认为同一人物。单字简称不据此跨段合并。'}</p>${profile?`<p>称呼：${E(profile.aliases.filter(a=>a.length>1).join('、'))}</p>`:`<h3>本段身份线索</h3><blockquote>${personExcerpt(current.o.slice(clueStart,clueStart+220),[mention.n,...(current.tokens||[]).filter(t=>toSimple(t.text)===mention.n).map(t=>t.text)])}</blockquote>`}${alternatives.length?`<h3>其他同名人物</h3>${alternatives.map(p=>`<button class="person-alternative" data-identity="${E(p.id)}">${E(p.name)} · ${E(p.era)}</button>`).join('')}`:''}<p class="search-status">同名异人分别保存；年代之外的追述、引文及身份不明记录不会强行归入档案。</p></aside><section class="person-occurrences"><div class="person-list-head"><strong>${profile?'关联出现':'同名线索'} ${rows.length} 段${anchor>=0?' · 当前第 '+(anchor+1)+' 段':''}</strong><div><button id="person-prev" ${pg===0?'disabled':''}>上一页</button><span>${pg+1} / ${pages}</span><button id="person-next" ${pg===pages-1?'disabled':''}>下一页</button></div></div>${visible.map((r,i)=>{let seg=chapters[i][r.s],p=seg.paragraphs[r.p],bookTitle=state.books.find(b=>b.id==='epub2').chapters[r.c].title,forms=[r.n,...r.forms],idx=Math.max(0,toSimple(p.o).indexOf(r.n)),start=Math.max(0,idx-55),excerpt=p.o.slice(start,start+200);return `<article class="person-occurrence ${r.c===mention.c&&r.s===mention.s&&r.p===mention.p?'current-person-occurrence':''}"><div class="person-occurrence-title"><span>${personYear(r.y)}</span><button data-location="${E(JSON.stringify({book:'epub2',chapter:r.c,segment:r.s,paragraph:r.p}))}">${E(bookTitle)} / ${E(seg.title)} / 第${r.p+1}段 ↗</button></div>${!profile?`<p class="identity-status">${r.who?'已有独立档案：'+E(data.profiles.find(x=>x.id===r.who)?.era||''):'本条身份待辨认'}</p>`:''}<p class="person-snippet">${start?'…':''}${personExcerpt(excerpt,forms.flatMap(n=>[n,...(p.tokens||[]).filter(t=>toSimple(t.text)===n).map(t=>t.text)]))}${start+200<p.o.length?'…':''}</p><details><summary>展开全文与译文</summary><p class="person-full-original">${personExcerpt(p.o,forms.flatMap(n=>[n,...(p.tokens||[]).filter(t=>toSimple(t.text)===n).map(t=>t.text)]))}</p>${p.t?`<p class="translated">${E(p.t)}</p>`:''}</details></article>`}).join('')}<button id="person-dismiss" class="primary">关闭</button></section></div>`;
  $('#person-prev').onclick=()=>personDialog(mentionId,identity,pg-1);$('#person-next').onclick=()=>personDialog(mentionId,identity,pg+1);$('#person-dismiss').onclick=()=>$('#dialog').close();$('#dialog-body').querySelectorAll('[data-identity]').forEach(b=>b.onclick=()=>personDialog(mentionId,b.dataset.identity,0));
 }catch{if(request===peopleRequest&&$('#dialog').classList.contains('person-dialog')){$('#dialog-body').innerHTML='<p>人物资料加载失败。</p><button id="person-retry" class="primary">重试</button>';$('#person-retry').onclick=()=>personDialog(mentionId,selectedIdentity,page)}}
}
