/* Historical place contexts and exact atlas text coordinates. */
const placeMapViews=new Map();
function placeAtlasKey(item){return item.path.replace(/^\/map_images\//,'').replace(/\.[^.]+$/,'')}
function placeMapChoices(atlas,matches,year){const ranked=[];for(const group of atlas)for(const item of group.items){const key=placeAtlasKey(item),hit=matches.find(x=>x.key===key);if(hit){const distance=Number.isFinite(year)?Math.max(group.start_year_int-year,year-group.end_year_int,0):Infinity;ranked.push({group,item,key,hit,distance})}}return ranked.sort((a,b)=>({'phrase_exact':0,'phrase_contains':1,'char_all':2}[a.hit.match_type]??3)-({'phrase_exact':0,'phrase_contains':1,'char_all':2}[b.hit.match_type]??3)||a.distance-b.distance||(b.hit.match_count||0)-(a.hit.match_count||0))}
function placeLabelGroups(points,name){const n=referenceNorm(name),groups=new Map();for(const p of points){const text=referenceNorm(p.text);if(!p.bbox||!text.includes(n))continue;let g=groups.get(p.text);if(!g){g={name:p.text,exact:text===n,points:[]};groups.set(p.text,g)}g.points.push(p)}return [...groups.values()].sort((a,b)=>Number(b.exact)-Number(a.exact)||b.points.length-a.points.length||a.name.localeCompare(b.name))}
function placeZoomAt(view,next,point){const zoom=Math.max(15,Math.min(1600,next)),ratio=zoom/view.zoom;return {zoom,x:point.x-(point.x-view.x)*ratio,y:point.y-(point.y-view.y)*ratio}}
referencePlace=async function(value,page=null){const {p,index}=referenceParts(value),place=p?.ExtRef_Children_places?.[index];if(!place)return;const stamp=referenceState.dialogStamp+1;openDialog('地名 · '+place.place_name,'<p>正在载入上下文与地图…</p>');$('#dialog').classList.add('place-dialog');try{let d=await referenceAPI('resolved_place_info',{place_tongjian_id:place.tongjian_id,page:page||1,page_size:10});let rows=d.occurrence_page||{items:[],current_page:1,total_pages:1};const anchorPage=Math.ceil((rows.anchor_paragraph_order||1)/(rows.page_size||10));if(page===null&&anchorPage!==rows.current_page){d=await referenceAPI('resolved_place_info',{place_tongjian_id:place.tongjian_id,page:anchorPage,page_size:10});rows=d.occurrence_page||rows}if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;const profile=d.resolved_profile||{},name=place.place_name_jianti_auto||place.place_name;
$('#dialog-body').innerHTML=`<div class="place-summary"><strong>${E(name)}</strong><p>${E(profile.intro||place.place_note||'暂无简介')}${profile.modern_location?' · 今地：'+E(profile.modern_location):''}</p></div><div class="place-layout"><section class="place-contexts" aria-label="地名相关上下文">${referencePaging(rows,'place',value)}${referenceOccurrences(rows)}</section><section class="place-map-panel" aria-label="历史地图"><div class="place-map-controls"><select id="place-map-sheet" aria-label="地名所在历史地图"><option>正在检索地图…</option></select><button id="place-map-minus" aria-label="缩小地图">−</button><button id="place-map-plus" aria-label="放大地图">＋</button><button id="place-map-center">定位地名</button><button id="place-map-native">原图大小</button><button id="place-map-fit">适应窗口</button><span id="place-map-scale" class="place-map-scale"></span></div><p class="place-map-status" id="place-map-status">正在匹配当前时代的地图…</p><div class="place-map-workspace"><aside class="place-map-results" id="place-map-results" aria-label="地图匹配与可能地点">正在检索可能地点…</aside><div class="place-map-canvas" id="place-map-canvas"><div class="place-map-stage" id="place-map-stage"><img id="place-map-image" alt="历史地图" hidden><div id="place-map-markers"></div></div></div></div></section></div>`;
$('.place-contexts').querySelectorAll('.person-occurrence').forEach((article,i)=>{const raw=rows.items[i]?.paragraph_brief?.paragraph;if(!raw)return;const text=String(raw.content||'').replace(/^\d+/,''),at=Math.max(0,referenceNorm(text).indexOf(referenceNorm(name))),projection=referenceProjection(text),start=Math.max(0,(projection.positions[at]||0)-50),excerpt=text.slice(start,start+210);article.querySelector('.person-snippet').innerHTML=(start?'…':'')+personExcerpt(excerpt,[place.place_name,name])+(start+210<text.length?'…':'');const details=article.querySelector('details');details.querySelector('summary').textContent='展开全文、译文与资料';details.querySelector('summary').insertAdjacentHTML('afterend',`<p class="place-full">${referencePlainOriginal(referenceStoreOccurrence(raw))}</p>`)});
const anchors=$('.place-contexts').querySelectorAll('[data-ref-jump]');anchors.forEach(el=>{if(el.dataset.refJump===(d.current_paragraph_tongjian_id||p.tongjian_id))el.closest('article').classList.add('place-anchor')});$('.place-anchor')?.scrollIntoView({block:'nearest'});await drawPlaceMap(value,name,p.year_int,stamp);
}catch(e){if(stamp===referenceState.dialogStamp&&$('#dialog').open)referenceError(e,()=>referencePlace(value,page))}};
async function drawPlaceMap(value,name,year,dialogStamp){const valid=()=>referenceState.dialogStamp===dialogStamp&&$('#place-map-image');try{
 const [atlas,matches]=await Promise.all([atlasData?Promise.resolve(atlasData):fetch('data/atlas.json').then(r=>r.json()),referenceAPI('map/search',{keyword:referenceNorm(name)})]);if(!valid())return;atlasData=atlas;
 const choices=placeMapChoices(atlas,matches,year);if(!choices.length){$('#place-map-status').textContent='暂未找到标注此地名的历史地图。';$('#place-map-results').textContent='暂无匹配地点';$('#place-map-sheet').disabled=true;return}
 const saved=placeMapViews.get(value)||{key:choices[0].key,zoom:null,x:0,y:0};placeMapViews.set(value,saved);
 const select=$('#place-map-sheet'),canvas=$('#place-map-canvas'),stage=$('#place-map-stage'),img=$('#place-map-image'),markers=$('#place-map-markers'),status=$('#place-map-status'),results=$('#place-map-results');
 select.innerHTML=choices.map(x=>`<option value="${E(x.key)}">${E(x.group.name+' / '+x.item.title)}</option>`).join('');select.value=choices.some(x=>x.key===saved.key)?saved.key:choices[0].key;
 let labels=[],groups=[],request=0,activeName=null;
 const apply=()=>{stage.style.width=canvas.clientWidth*(saved.zoom||100)/100+'px';stage.style.transform=`translate(${saved.x}px,${saved.y}px)`;$('#place-map-scale').textContent=img.naturalWidth?Math.round(canvas.clientWidth*(saved.zoom||100)/img.naturalWidth)+'% 原图':'';canvas.dataset.zoom=String(saved.zoom);canvas.dataset.panX=String(saved.x);canvas.dataset.panY=String(saved.y)};
 const focus=(points,fit=false)=>{if(!img.naturalWidth||!canvas.clientWidth)return;const base=canvas.clientWidth/img.naturalWidth;if(fit){saved.zoom=Math.min(100,canvas.clientHeight/(img.naturalHeight*base)*100);saved.x=(canvas.clientWidth-canvas.clientWidth*saved.zoom/100)/2;saved.y=(canvas.clientHeight-img.naturalHeight*base*saved.zoom/100)/2}else if(points.length){const left=Math.min(...points.map(p=>p.bbox.left)),right=Math.max(...points.map(p=>p.bbox.left+p.bbox.width)),top=Math.min(...points.map(p=>p.bbox.top)),bottom=Math.max(...points.map(p=>p.bbox.top+p.bbox.height));saved.x=canvas.clientWidth/2-(left+right)/2*base*saved.zoom/100;saved.y=canvas.clientHeight/2-(top+bottom)/2*base*saved.zoom/100}apply()};
 const zoom=(n,point={x:canvas.clientWidth/2,y:canvas.clientHeight/2})=>{Object.assign(saved,placeZoomAt({...saved,zoom:saved.zoom||100},n,point));apply()};
 const paint=()=>{markers.innerHTML=labels.map(p=>`<span class="place-map-marker ${activeName===p.text?'active':''}" title="${E(p.text)}" style="left:${(p.bbox.left+p.bbox.width/2)/img.naturalWidth*100}%;top:${(p.bbox.top+p.bbox.height/2)/img.naturalHeight*100}%"></span>`).join('')};
 const showResults=()=>{const exact=groups.filter(g=>g.exact),possible=groups.filter(g=>!g.exact);results.innerHTML=`<h4>${E(name)} · 地图文字匹配</h4><small>同字地点可能有多处，可逐项定位</small><h5>精确匹配</h5>${exact.map(g=>`<button class="place-match" data-place-label="${E(g.name)}">${E(g.name)} <span>(${g.points.length})</span></button>`).join('')||'<p>此图暂无精确匹配</p>'}<h5>可能的位置 · 包含匹配</h5>${possible.map(g=>`<button class="place-match" data-place-label="${E(g.name)}">${E(g.name)} <span>(${g.points.length})</span></button>`).join('')||'<p>暂无其他候选地点</p>'}<h5>其他地图</h5>${choices.filter(c=>c.key!==select.value).map(c=>`<button class="place-map-choice" data-place-map="${E(c.key)}">${E(c.group.name+' / '+c.item.title)}<small>${c.hit.match_type==='phrase_exact'?'精确匹配':c.hit.match_type==='phrase_contains'?'包含匹配':'模糊匹配'} (${c.hit.match_count||0})</small></button>`).join('')}`;results.scrollTop=0};
 $('#place-map-minus').onclick=()=>zoom((saved.zoom||100)/1.2);$('#place-map-plus').onclick=()=>zoom((saved.zoom||100)*1.2);$('#place-map-center').onclick=()=>focus(activeName?labels.filter(p=>p.text===activeName):labels);$('#place-map-fit').onclick=()=>focus([],true);$('#place-map-native').onclick=()=>zoom(img.naturalWidth/canvas.clientWidth*100);
 const load=async()=>{const choice=choices.find(x=>x.key===select.value),current=++request;saved.key=choice.key;status.textContent='正在载入 '+choice.group.name+' / '+choice.item.title+'…';img.hidden=true;markers.replaceChildren();try{
 const [url,points]=await Promise.all([referenceAPI('map/image-url',{oss_filename:choice.item.oss_filename}),referenceAPI('map/labels',{key:choice.key})]);if(!valid()||current!==request)return;
 groups=placeLabelGroups(points,name);labels=groups.flatMap(g=>g.points);activeName=null;showResults();
 img.onload=()=>{if(!valid()||current!==request)return;img.hidden=false;paint();status.textContent=choice.group.name+' / '+choice.item.title+' · '+labels.length+' 处候选标注 · 滚轮缩放，拖动移动';if(saved.zoom===null){saved.zoom=Math.min(1600,img.naturalWidth/canvas.clientWidth*100);focus(labels.slice(0,1));if(!labels.length)apply()}else apply()};
 img.onerror=()=>{if(valid())status.textContent='地图载入失败，请重新选择地图重试。'};img.alt=choice.group.name+' / '+choice.item.title;img.draggable=false;img.src=url.image_url;
 }catch(e){if(valid()&&current===request){status.textContent='地图资料暂不可用：'+e.message;results.textContent='匹配资料载入失败，请重新选择地图重试。'}}};
 const change=key=>{select.value=key;saved.zoom=null;saved.x=saved.y=0;load()};select.onchange=()=>change(select.value);
 results.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.placeMap)change(b.dataset.placeMap);else if(b.dataset.placeLabel){activeName=b.dataset.placeLabel;results.querySelectorAll('[data-place-label]').forEach(el=>el.classList.toggle('active',el===b));const points=labels.filter(p=>p.text===activeName);saved.zoom=Math.max(saved.zoom||100,150);paint();focus(points)}};
 canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom((saved.zoom||100)*Math.exp(-Math.max(-100,Math.min(100,e.deltaY))*.002),{x:e.clientX-r.left,y:e.clientY-r.top})},{passive:false});
 let drag=null;canvas.onpointerdown=e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,left:saved.x,top:saved.y};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging');e.preventDefault()};canvas.onpointermove=e=>{if(drag){saved.x=drag.left+e.clientX-drag.x;saved.y=drag.top+e.clientY-drag.y;apply()}};canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;canvas.classList.remove('dragging')};await load();
 }catch(e){if(valid())$('#place-map-status').textContent='地图资料暂不可用：'+e.message}}
const placesOpenDialog=openDialog;openDialog=function(title,html){$('#dialog').classList.remove('place-dialog');return placesOpenDialog(title,html)};
