/* Reading controls. Existing paragraph IDs and stored reading records are preserved. */
'use strict';
const readingDefaults={size:20,line:1.7,font:'serif',translationFont:'wenkai',translationSize:18,theme:'light',translation:true,parallel:true,notes:true,annotations:false,simplified:false,pinyin:true,life:false,age:true,hoverLink:true,clickLink:true,emphasis:'lines',spacing:0,width:1440,noteStyle:'line',noteColor:'red',ganzhi:true,paragraphTools:true};
state.settings={...readingDefaults,...state.settings};
if(!state.settings.compactLayoutV1){Object.assign(state.settings,{line:1.7,spacing:0,width:1440,compactLayoutV1:true});persist()}
const readingFonts={noto:'思源宋体',wenkai:'霞鹜文楷',serif:'设备宋体',kai:'设备楷体',sans:'黑体'};fonts.noto='"ReaderNoto",'+fonts.serif;fonts.wenkai='"ReaderWenKai",'+fonts.kai;
const rareSounds={蜹:'ruì',狃:'niǔ',鼃:'wā',絺:'chī',悛:'quān',繇:'yóu',惓:'quán',跗:'fū',筮:'shì',轸:'zhěn',戮:'lù',刖:'yuè',黥:'qíng',髡:'kūn',杌:'wù',俎:'zǔ',觚:'gū',觥:'gōng',兕:'sì',罴:'pí',羆:'pí',阍:'hūn',閽:'hūn',谶:'chèn',讖:'chèn',赀:'zī',貲:'zī',赍:'jī',齎:'jī',禳:'ráng',醢:'hǎi',菹:'zū',胙:'zuò',鬯:'chàng',纛:'dào',旄:'máo',旒:'liú',钺:'yuè',鉞:'yuè',衮:'gǔn',袞:'gǔn',鞫:'jū',窳:'yǔ',斫:'zhuó',轭:'è',軛:'è',糴:'dí',籴:'dí',糶:'tiào',粜:'tiào',耄:'mào',耋:'dié',獬:'xiè',豸:'zhì',觇:'chān',覘:'chān',谳:'yàn',讞:'yàn'};
function readingText(text){let t=state.settings.simplified?toSimple(text):String(text);let out=[...t].map(c=>state.settings.pinyin&&rareSounds[c]?`<ruby>${E(c)}<rt>${rareSounds[c]}</rt></ruby>`:E(c)).join('');if(state.settings.ganzhi)out=out.replace(/([甲乙丙丁戊己庚辛壬癸][子丑寅卯辰巳午未申酉戌亥])(?=[，、。])/g,'<button class="ganzhi-day" data-ganzhi="$1" title="查看干支纪日">$1</button>');return out}
function captureReadingQuote(original){const selection=window.getSelection();if(!selection?.rangeCount)return '';const fragment=selection.getRangeAt(0).cloneContents();const temp=document.createElement('div');temp.append(fragment);temp.querySelectorAll('rt,.annotation-label,.annotation-inline,.life-label').forEach(n=>n.remove());const chosen=temp.textContent.trim();if(!chosen)return '';if(original.includes(chosen))return chosen;const i=toSimple(original).indexOf(toSimple(chosen));return i>=0?original.slice(i,i+chosen.length):''}
function redrawReading(){if(!segments[state.segment])return;const p=state.paragraph;applySettings();renderContent();jumpTo(p);persist()}
const baseApplySettings=applySettings;
applySettings=function(){baseApplySettings();let s=state.settings;let root=document.documentElement;root.style.setProperty('--translation-font',fonts[s.translationFont]||fonts.kai);root.style.setProperty('--translation-size',s.translationSize+'px');root.style.setProperty('--letter-spacing',s.spacing+'em');root.style.setProperty('--reading-width',s.width+'px');root.style.setProperty('--note-color',({red:'#c66464',blue:'#6098ce',yellow:'#bfa02b',amber:'#bf853b'})[s.noteColor]);document.body.dataset.emphasis=s.emphasis;document.body.dataset.noteStyle=s.noteStyle;document.body.dataset.hoverLink=s.hoverLink;document.body.dataset.paragraphTools=s.paragraphTools;};
renderOriginal=function(r){if(!r.tokens)return readingText(r.o);let ni=0;return r.tokens.map(t=>{if(t.kind==='image')return `<img class="original-glyph" src="${E(t.src)}" alt="原书异体字形">`;if(t.note){const j=ni++;return state.settings.annotations?`<span class="annotation-inline">〔${noteHTML(t)}〕</span>`:`<button class="annotation-label" data-inline-note="${j}" aria-label="查看第${j+1}条胡注">〔注〕</button>`}if(t.kind==='name'&&t.personMention!==undefined)return `<button class="entity-name person-name" data-person="${t.personMention}" aria-label="查看人物 ${E(t.text)}">${displayText(t.text)}</button>`;return `<span class="entity-${E(t.kind||'text')}">${t.kind==='text'?readingText(t.text):displayText(t.text)}</span>`}).join('')};
const baseRenderContent=renderContent;
renderContent=function(){baseRenderContent();const cfg=state.settings;const seg=segments[state.segment];let title=seg.title.match(/^(.*?)\s+([^\s]*年)（(.*?)）$/);if(title){$('#content h1').innerHTML=displayText(title[2])+`<small class="era-heading">${displayText(title[1])}${cfg.ganzhi?' · '+displayText(title[3]):''}</small>`}document.querySelectorAll('.paragraph').forEach((section,i)=>{const r=seg.paragraphs[i];section.querySelector('.paragraph-actions').insertAdjacentHTML('beforeend',`<button class="source-button" data-source="${i}">底本</button><span class="tag-label">标签</span>${(state.tags[key(i)]||[]).map(t=>`<button class="tag" data-tag-search="${E(t)}">${E(t)}</button>`).join('')}<button data-edit-tags="${i}" aria-label="编辑第${i+1}段标签">＋</button>`);const note=state.notes[key(i)];if(note?.quote)markQuote(section.querySelector('.original'),state.settings.simplified?toSimple(note.quote):note.quote);const tr=section.querySelector('.translated');if(tr){tr.tabIndex=0;tr.setAttribute('aria-label',`第${i+1}段白话文`);tr.dataset.translation=i;tr.querySelector('.translation-label')?.remove()} });if(cfg.life||cfg.age)decorateLife();updateReadingProgress();};
let lifePaint=0;
function personAgeAtYear(birth,year,death){if(!Number.isInteger(birth)||!Number.isInteger(year)||birth===0||year===0||year<birth||(Number.isInteger(death)&&year>death))return null;const age=year-birth-(birth<0&&year>0?1:0);return age<100?age:null}
async function decorateLife(){const stamp=++lifePaint,loc=`${state.book}:${state.chapter}:${state.segment}`;if(state.book!=='epub2')return;try{const idx=await peopleIndex();if(stamp!==lifePaint||(!state.settings.life&&!state.settings.age)||loc!==`${state.book}:${state.chapter}:${state.segment}`)return;const profiles=new Map(idx.profiles.map(p=>[p.id,p]));document.querySelectorAll('#content [data-person]').forEach(el=>{const m=idx.occurrences[+el.dataset.person],p=profiles.get(m?.who);if(!p)return;let anchor=el;const age=p.lifespanUncertain||p.birthStatus&&p.birthStatus!=='year'?null:personAgeAtYear(p.birth,m.y,p.death);if(state.settings.age&&age!==null&&!el.closest('.person-age')){const ruby=document.createElement('ruby');ruby.className='person-age';el.before(ruby);ruby.append(el);const rt=document.createElement('rt');rt.className='age-label';rt.textContent=age+'岁';rt.title=personYear(m.y)+'时的年差年龄（未按生日细分）';ruby.append(rt);anchor=ruby}if(state.settings.life&&!anchor.nextElementSibling?.classList.contains('life-label')){const label=document.createElement('sup');label.className='life-label';label.textContent=personLife(p);label.title=p.name+' · '+p.bio;anchor.after(label)}})}catch{toast('人物辅助资料载入失败，可稍后重试')}}
function markQuote(root,quote){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const entries=[];let n,text='';while(n=walker.nextNode()){if(n.parentElement.closest('rt,.annotation-inline,.annotation-label,.life-label'))continue;entries.push({node:n,start:text.length,end:text.length+n.textContent.length});text+=n.textContent}const begin=text.indexOf(quote);if(begin<0)return;const end=begin+quote.length;for(const entry of entries){if(entry.end<=begin||entry.start>=end)continue;const range=document.createRange();range.setStart(entry.node,Math.max(0,begin-entry.start));range.setEnd(entry.node,Math.min(entry.node.length,end-entry.start));const mark=document.createElement('mark');mark.className='my-annotation';range.surroundContents(mark)}}
function choiceSetting(name,label,items){return `<fieldset class="reading-choice"><legend>${label}</legend>${Object.entries(items).map(([v,l])=>`<label><input type="radio" name="${name}" value="${v}" data-setting="${name}" ${state.settings[name]===v?'checked':''}>${l}</label>`).join('')}</fieldset>`}
function rangeSetting(name,label,min,max,step,suffix=''){return `<div class="setting"><label for="cfg-${name}">${label} <output id="${name}-out">${state.settings[name]}${suffix}</output></label><input id="cfg-${name}" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${state.settings[name]}" data-setting="${name}" data-suffix="${suffix}"></div>`}
function checkboxSettings(items){return `<div class="reading-checks">${Object.entries(items).map(([v,l])=>`<label><input type="checkbox" data-setting="${v}" ${state.settings[v]?'checked':''}>${l}</label>`).join('')}</div>`}
settingsDialog=function(){openDialog('阅读配置',`<h3>批注展开</h3>${checkboxSettings({annotations:'胡三省注与校注',notes:'我的批注'})}<h3>正文与白话文</h3>${checkboxSettings({simplified:'简体',translation:'白话文',pinyin:'拼音（常见生僻字）',parallel:'左右对照',hoverLink:'悬停联动',clickLink:'点击联动'})}<p class="search-status">悬停时标记整段对应译文；点击句子在上方查看对应译文，两侧对应文字下方显示横线。生僻字拼音为常用读音提示，多音字请结合胡注。</p><h3>辅助</h3>${checkboxSettings({ganzhi:'标题干支纪年',life:'人物生卒',age:'人物年龄',paragraphTools:'段落工具栏'})}<p class="search-status">年龄按本段纪年与出生年计算，显示在人名上方，未按生日细分。身份或出生年不明时不显示年龄。</p>${rangeSetting('size','正文字号',14,40,1,'px')}${rangeSetting('translationSize','白话文字号',14,40,1,'px')}${choiceSetting('font','正文字体',readingFonts)}${choiceSetting('translationFont','白话文字体',readingFonts)}<p class="search-status">内置思源宋体与霞鹜文楷，也可载入京華老宋、上图东观等自己的字体文件。</p><div class="row"><label class="font-upload">载入正文自选字体 <input type="file" id="original-font-file" accept=".woff,.woff2,.ttf,.otf"></label><label class="font-upload">载入白话自选字体 <input type="file" id="translation-font-file" accept=".woff,.woff2,.ttf,.otf"></label></div>${choiceSetting('theme','背景模式',{light:'正常',eye:'护眼',dark:'夜间'})}${choiceSetting('emphasis','语义强调',{color:'颜色',lines:'线条',bold:'仅加粗',none:'无'})}<h3>高级样式</h3>${choiceSetting('noteStyle','选文批注样式',{line:'细线',thick:'粗线',background:'背景',text:'文字'})}${choiceSetting('noteColor','批注颜色',{red:'红色',blue:'蓝色',yellow:'黄色',amber:'琥珀色'})}<p class="search-status">选中文字后点“写批注”，保存后标记这段选文。</p>${rangeSetting('line','行间距',1.5,3,.1)}${rangeSetting('spacing','字间距',0,.15,.01,'em')}${rangeSetting('width','阅读栏最大宽度',560,1600,40,'px')}<div class="row"><button id="reset-settings">恢复默认</button><button id="close-reading-settings" class="primary">完成</button></div>`);$('#dialog').classList.add('settings-dialog');$('#dialog-body').querySelectorAll('[data-setting]').forEach(el=>el.oninput=()=>{const name=el.dataset.setting;state.settings[name]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;const out=$('#'+name+'-out');if(out)out.textContent=el.value+(el.dataset.suffix||'');redrawReading()});$('#reset-settings').onclick=()=>{state.settings={...readingDefaults};redrawReading();settingsDialog()};$('#close-reading-settings').onclick=()=>$('#dialog').close();for(const [id,name] of [['original-font-file','font'],['translation-font-file','translationFont']])$('#'+id).onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const family='ReaderCustom'+name;const face=new FontFace(family,await file.arrayBuffer());await face.load();document.fonts.add(face);fonts[family]='"'+family+'"';readingFonts[family]=file.name;state.settings[name]=family;redrawReading();toast('字体已应用，本次页面有效')}catch{toast('字体无法读取，请选择有效字体文件')}}};
actions.settings=()=>settingsDialog();
function translationDialog(p){const r=segments[state.segment].paragraphs[p];openDialog('文白对照',`<p class="search-status">${E(segments[state.segment].title)} · 第 ${p+1} 段</p><div class="translation-card" data-paragraph-id="${p}"><p class="original">${renderOriginal(r)}</p><p class="translated">${r.t?E(r.t):'本段译文待补'}</p></div><div class="row"><button data-detail="${p}">胡注与批注</button><button data-note="${p}">写批注</button><button data-copy="${p}">复制段落链接</button></div>`)}
function tagsDialog(p){const current=state.tags[key(p)]||[];openDialog('段落标签',`<p class="search-status">第${p+1}段 · 自己整理的标签保存在本地</p><input id="tag-input" aria-label="标签内容" placeholder="用逗号分隔，例如：军事、人事、史论" value="${E(current.join('，'))}" style="width:100%"><div class="row">${['军事','人事','内政','外交','权争','史论'].map(t=>`<button data-suggest-tag="${t}">${t}</button>`).join('')}</div><button id="save-tags" class="primary">保存标签</button>`);$('#dialog-body').querySelectorAll('[data-suggest-tag]').forEach(b=>b.onclick=()=>{let vals=$('#tag-input').value.split(/[,，、]/).map(x=>x.trim()).filter(Boolean);if(!vals.includes(b.dataset.suggestTag))vals.push(b.dataset.suggestTag);$('#tag-input').value=vals.join('，')});$('#save-tags').onclick=()=>{state.tags[key(p)]=[...new Set($('#tag-input').value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean))];persist();$('#dialog').close();const pos=$('#reading').scrollTop;renderContent();$('#reading').scrollTop=pos;toast('标签已保存')}}
function taggedParagraphs(tag){const rows=Object.entries(state.tags).filter(([,tags])=>tags.includes(tag));openDialog('标签 · '+tag,rows.map(([k])=>{const [b,c,s,p]=k.split(':');const title=state.books.find(x=>x.id===b)?.chapters[+c]?.segments[+s]||'';return `<button class="result" data-location="${E(JSON.stringify({book:b,chapter:+c,segment:+s,paragraph:+p}))}">${E(title)} · 第${+p+1}段</button>`}).join('')||'<p class="empty">暂无关联段落</p>')}
function pathDialog(){const seg=segments[state.segment];openDialog('路径导航',`<p>${E(book().title)} / ${E(book().chapters[state.chapter].title)}</p><label for="jump-paragraph">跳转段落（共 ${seg.paragraphs.length} 段）</label><form id="jump-form" class="row"><input id="jump-paragraph" type="number" min="1" max="${seg.paragraphs.length}" value="${state.paragraph+1}" aria-label="段落编号"><button class="primary">跳转</button></form><h3>本卷纪年</h3>${segments.map((s,i)=>`<button class="result" data-chapter="${state.chapter}" data-segment="${i}">${E(s.title)}</button>`).join('')}`);$('#jump-form').onsubmit=e=>{e.preventDefault();const p=Math.max(0,Math.min(seg.paragraphs.length-1,Number($('#jump-paragraph').value)-1));$('#dialog').close();jumpTo(p)};$('#dialog-body').querySelectorAll('[data-chapter]').forEach(b=>b.addEventListener('click',()=>$('#dialog').close()))}
function sourceDialog(p){const r=segments[state.segment].paragraphs[p];openDialog('底本文字',`<p class="search-status">来自当前 EPUB · ${E(book().chapters[state.chapter].title)} · 第${p+1}段</p><p class="original">${E(r.o)}</p>${r.annotations?.length?'<h3>底本注释</h3>'+r.annotations.map(n=>`<p class="annotation-full">${displayText(n)}</p>`).join(''):''}<p class="search-status">此处展示电子底本文字；本版未接入古籍扫描影像。</p>`)}
document.addEventListener('click',e=>{const note=e.target.closest('[data-inline-note]');if(note){e.preventDefault();e.stopImmediatePropagation();const p=+(note.closest('.paragraph')?.dataset.p??note.closest('[data-paragraph-id]')?.dataset.paragraphId);const r=segments[state.segment].paragraphs[p];const token=r.tokens.filter(t=>t.note)[+note.dataset.inlineNote];openDialog('胡三省注与校注',`<p class="search-status">第${p+1}段 · 第${+note.dataset.inlineNote+1}条注释</p><p class="annotation-full">${noteHTML(token)}</p><button data-detail="${p}">查看本段全部注释与批注</button>`);return}const b=e.target.closest('button');if(!b)return;if(b.dataset.ganzhi){e.preventDefault();e.stopImmediatePropagation();const signs=Array.from({length:60},(_,i)=>'甲乙丙丁戊己庚辛壬癸'[i%10]+'子丑寅卯辰巳午未申酉戌亥'[i%12]);openDialog('干支纪日 · '+b.dataset.ganzhi,`<p>六十甲子中的第 ${signs.indexOf(b.dataset.ganzhi)+1} 位。十天干与十二地支顺次相配，每六十日一循环。</p><div class="sexagenary-grid">${signs.map(s=>`<span class="${s===b.dataset.ganzhi?'current-sign':''}">${s}</span>`).join('')}</div><p class="search-status">这里只解释干支顺序，具体公历日期须结合本年月份和历法考证。</p>`);return}if(b.dataset.editTags!==undefined)tagsDialog(+b.dataset.editTags);if(b.dataset.tagSearch)taggedParagraphs(b.dataset.tagSearch);if(b.dataset.source!==undefined)sourceDialog(+b.dataset.source);if(b.dataset.action==='path')pathDialog();if(b.dataset.action==='focus')document.body.classList.toggle('focus-reading');if(b.dataset.action==='top')$('#reading').scrollTo({top:0,behavior:'smooth'});if(b.dataset.action==='leave-focus')document.body.classList.remove('focus-reading')},true);
// The source and translation are aligned by paragraph, without guessing sentence matches.
$('#reading').addEventListener('mouseover',e=>{if(!state.settings.hoverLink)return;const text=e.target.closest('.original,.translated');if(text)text.closest('.texts')?.classList.add('linked-paragraph')});
$('#reading').addEventListener('mouseout',e=>{const group=e.target.closest('.texts');if(group&&!group.contains(e.relatedTarget))group.classList.remove('linked-paragraph')});
$('#reading').addEventListener('click',e=>{const tr=e.target.closest('[data-translation]');if(tr&&state.settings.clickLink)translationDialog(+tr.dataset.translation)});
const toolsBar=document.createElement('div');toolsBar.className='reader-bottom-tools';toolsBar.innerHTML='<span id="read-progress">0%</span><button data-action="path" title="跳转到指定段落">定位</button><button data-action="focus" title="隐藏侧栏专心阅读">专注</button><button data-action="top" title="回到章首">↑</button>';$('#reading').append(toolsBar);
$('#path').tabIndex=0;$('#path').setAttribute('role','button');$('#path').setAttribute('aria-label','打开路径导航');$('#path').onclick=pathDialog;$('#path').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')pathDialog()};
const focusExit=document.createElement('button');focusExit.className='focus-exit';focusExit.dataset.action='leave-focus';focusExit.textContent='退出专注';document.body.append(focusExit);
function updateReadingProgress(){const r=$('#reading');$('#read-progress').textContent=Math.round(100*r.scrollTop/Math.max(1,r.scrollHeight-r.clientHeight))+'%'}
$('#reading').addEventListener('scroll',updateReadingProgress,{passive:true});
document.addEventListener('keydown',e=>{if($('#dialog').open||e.target.matches('input,textarea,select')||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='ArrowLeft'){e.preventDefault();if(!$('#prev').disabled)$('#prev').click()}if(e.key==='ArrowRight'){e.preventDefault();if(!$('#next').disabled)$('#next').click()}if(e.key==='Escape')document.body.classList.remove('focus-reading');if(e.key==='Home'){e.preventDefault();$('#reading').scrollTop=0}if(e.key==='End'){e.preventDefault();$('#reading').scrollTop=$('#reading').scrollHeight}});
const baseRenderTree=renderTree;
renderTree=function(){baseRenderTree();if($('#toc-filter').value)return;document.querySelectorAll('#tree>details').forEach(d=>{const buttons=[...d.querySelectorAll('.year')];let current,group;for(const b of buttons){const match=b.textContent.match(/^(.*?)\s+([^\s]*年[（(].*)$/);if(!match)continue;if(current!==match[1]){current=match[1];group=document.createElement('details');group.className='ruler-group';group.open=!!buttons.find(x=>x.classList.contains('active')&&x.textContent.startsWith(current+' '));const summary=document.createElement('summary');summary.textContent=current;group.append(summary);d.insertBefore(group,b)}b.textContent=match[2];group.append(b)}})};
applySettings();if(segments[state.segment]){renderTree();renderContent()}

actions.symbols=()=>openDialog("阅读符号说明",symbolGuideHTML()+'<p class="symbol-page-link"><a href="symbols.html" target="_blank" rel="noopener">单独打开说明页 ↗</a></p>');
