/* Public reading supplements, matched to the user's EPUB paragraph by paragraph. */
'use strict';
function referenceCheckedDates(item,p){const known=referenceState.profileByQ.get(item.link_td_id);const full=referenceNorm(item.people_xingming||''),body=referenceNorm(p.content||'');
 const short=referenceNorm(item.people_name||'');const titleTarget=short==='太祖'&&body.includes('太祖诸子俱尽')&&body.includes('建平王景素')?'Q49702':short==='高祖'&&body.includes('高祖疾亟')&&body.includes('刘知远入辅政')?'Q1189495':null;
 if(titleTarget){const target=referenceState.profileByQ.get(titleTarget);if(target)return {...item,link_td_id:titleTarget,local_identity:target.id,people_xingming:target.name,link_birth_year:target.birth,link_death_year:target.death,link_birth_text:target.birthText,link_death_text:target.deathText,link_td_description:target.bio};}
 if((known?.id==='liu-xiu-han'||/光武/.test(item.link_td_description||''))&&full==='刘秀'&&/国师.{0,5}刘秀|刘秀.{0,10}更名|刘歆.{0,20}秀/.test(body))return {...item,link_td_id:null,link_td_number_id:null,link_birth_year:null,link_death_year:null,link_td_description:'本段国师刘秀应与光武帝刘秀分别辨认，未沿用光武帝的人物编号。'};
 if(!known)return item;
 if(Number.isInteger(p.year_int)&&Number.isInteger(known.birth)&&p.year_int<known.birth-1)return {...item,link_td_id:null,link_td_number_id:null,link_birth_year:null,link_death_year:null,link_td_description:'段落年代早于该人物出生年，人物编号有冲突，暂不合并。'};
 const name=referenceNorm(known.name||''),aliases=[known.name,...known.aliases,...(known.contextAliases||[])].map(referenceNorm);
 if(full.length>=2&&full.length<=4&&name.length>=2&&name.length<=4&&!/(?:王|侯|公|帝|皇|君|后|子|氏)$/.test(full)&&!/(?:王|侯|公|帝|皇|君|后|子|氏)$/.test(name)&&!aliases.includes(full))return {...item,link_td_id:null,link_td_number_id:null,link_birth_year:null,link_death_year:null,link_td_description:'明确姓名与人物档案不一致，身份待辨认，未合并到该人物。'};
 if(known.lifespanUncertain)return {...item,link_birth_year:null,link_death_year:null,link_birth_text:'生卒记载待核',dates_uncertain:true};
 if(!known.dateAudit)return item;const result={...item};for(const key of ['birth','death']){const field='link_'+key+'_year',status=known[key+'Status'];if(status&&status!=='year'){result[field]=null;result['link_'+key+'_text']=known[key+'Text']||null;result.dates_uncertain=true}else if(Number.isInteger(result[field])&&Number.isInteger(known[key])&&result[field]!==known[key]){result[field]=null;result['link_'+key+'_text']=key==='birth'?'生年有异说':'卒年有异说';result.dates_uncertain=true}}return result}
function referenceProfileLife(person){return (person.link_birth_text|| (person.link_birth_year==null?'生年不详':personYear(person.link_birth_year)))+'—'+(person.link_death_text||(person.link_death_year==null?'卒年不详':personYear(person.link_death_year)))}
function referenceCorrectParagraph(p){const people=p.ExtRef_Children_people||[];return {...p,ExtRef_Children_people:people.map(item=>{
 const full=referenceNorm(item.people_xingming||item.people_name||''),short=referenceNorm(item.people_name||'');item=referenceCheckedDates(item,p);
 if(item.link_td_id==='Q10007449'&&(full==='刘恭'||short==='刘恭'||short==='恭'&&(referenceNorm(p.content).includes('刘恭')||people.some(x=>referenceNorm(x.people_xingming||'')==='刘恭'))))return {...item,link_td_id:'local-liugong-chimei',local_profile:'liugong-chimei',people_xingming:'刘恭',link_td_number_id:null,link_birth_year:null,link_death_year:null,link_td_description:'刘盆子的兄长。曾受赤眉派遣向光武帝请求投降，后为更始帝报仇，杀谢禄并自系狱，获赦。'};
 const canonical=referenceNorm((item.link_td_description||'').split(/[，,。；;]/)[0]);
 const canonicalMention=canonical.length>=2&&canonical.length<=5&&!/(?:王|侯|公|帝|皇|君|后|子)$/.test(canonical)&&people.some(other=>other.link_td_id===item.link_td_id&&referenceNorm(other.people_xingming||other.people_name||'')===canonical);
 if(item.link_td_id&&full.length>=2&&full!==canonical&&canonicalMention&&!canonical.endsWith(full))return {...item,link_td_id:null,link_td_number_id:null,link_birth_year:null,link_death_year:null,link_td_description:'本条姓名与原资料人物简介冲突，身份待辨认，未沿用原人物编号。'};
 return item
 })}}
const referenceState={map:null,pending:new Map(),stamp:0,dialogStamp:0,paragraphs:new Map(),names:[],suffixes:new Map(),profileByQ:new Map()};
if(state.settings.reference===undefined)state.settings.reference=true;
if(!state.settings.referenceDisplayV1){state.settings.life=true;state.settings.referenceDisplayV1=true;persist()}
const referenceStatus=document.createElement('button');referenceStatus.className='reference-status';referenceStatus.dataset.action='reference';referenceStatus.textContent='补充阅读资料';$('#tools .tool-body').prepend(referenceStatus);
const referenceOnlineCache=new Map();
async function referenceAPI(endpoint,params={}){const cacheKey=endpoint+JSON.stringify(params);const cached=referenceOnlineCache.get(cacheKey);if(cached&&Date.now()<cached.until)return cached.data;const query=new URLSearchParams({endpoint,...params});const r=await fetch('https://emmaphvutiiawhmluhvr.supabase.co/functions/v1/tongjian-reference?'+query,{headers:{Authorization:'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbWFwaHZ1dGlpYXdobWx1aHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk3Njk2MzgsImV4cCI6MjEwNTM0NTYzOH0.DrKvjwtoh2W-pLdp1OdTEWvTZp_wIQn1SGQQssxxGiE',apikey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbWFwaHZ1dGlpYXdobWx1aHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk3Njk2MzgsImV4cCI6MjEwNTM0NTYzOH0.DrKvjwtoh2W-pLdp1OdTEWvTZp_wIQn1SGQQssxxGiE'}});if(!r.ok)throw Error('补充资料暂不可用，请稍后重试');const d=await r.json();if(d.success===false)throw Error(d.message||'资料暂不可用');referenceOnlineCache.set(cacheKey,{data:d.data,until:Date.now()+(endpoint==='map/image-url'?40000:3600000)});return d.data}
function referenceNorm(s){return toSimple(String(s||'')).replace(/衞/g,'卫').replace(/爲/g,'为').replace(/於/g,'于').replace(/羣/g,'群').replace(/餘/g,'余').replace(/[^\p{Script=Han}]/gu,'')}
function referenceProjection(text){let normalized='',positions=[];for(let i=0;i<text.length;i++){const c=referenceNorm(text[i]);if(c){normalized+=c;positions.push(i)}}return {normalized,positions}}
function referenceScore(a,b){if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .85*Math.min(a.length,b.length)/Math.max(a.length,b.length)+.15;const grams=s=>new Set(Array.from({length:Math.max(0,s.length-1)},(_,i)=>s.slice(i,i+2))),aa=grams(a),bb=grams(b);let both=0;for(const g of aa)if(bb.has(g))both++;return 2*both/Math.max(1,aa.size+bb.size)}
function matchReferenceParagraphs(local,remote){const matches=[];let last=-1;const normalized=remote.map(p=>referenceNorm(p.content));for(let i=0;i<local.length;i++){const a=referenceNorm(local[i].o);let best=-1,score=0;for(let j=Math.max(0,last-1);j<remote.length;j++){const q=referenceScore(a,normalized[j]);if(q>score){best=j;score=q}}if(score>=.7){matches.push({local:i,remote:best,score});last=Math.max(last,best)}}return matches}
function referenceRanges(text,p){const local=referenceProjection(text),source=String(p.content||''),remote=referenceProjection(source),ranges=[];const groups=[['person',p.ExtRef_Children_people,'people_name'],['place',p.ExtRef_Children_places,'place_name'],['official',p.ExtRef_Children_officials,'official_name'],['pinyin',p.ExtRef_Children_pinyin,'']];for(const [kind,list,field] of groups)for(const [index,item] of (list||[]).entries()){
 if(kind==='person'&&referenceIdentityConflict(text,item))continue;const name=item[field]||item.word||item.character||item.char||item.text||item.content||item.hanzi;if(!name)continue;const n=referenceNorm(name);if(!n)continue;const prefix=referenceNorm(source.slice(0,item.start_index||0)).length;let at=-1;
 if(local.normalized===remote.normalized&&local.normalized.slice(prefix,prefix+n.length)===n)at=prefix;
 else {let cursor=0,score=-Infinity;while((cursor=local.normalized.indexOf(n,cursor))>=0){const before=local.normalized.slice(Math.max(0,cursor-12),cursor),after=local.normalized.slice(cursor+n.length,cursor+n.length+12);const rb=remote.normalized.slice(Math.max(0,prefix-12),prefix),ra=remote.normalized.slice(prefix+n.length,prefix+n.length+12);const q=referenceScore(before,rb)+referenceScore(after,ra)-.3*Math.abs(cursor/Math.max(1,local.normalized.length)-prefix/Math.max(1,remote.normalized.length));if(q>score){score=q;at=cursor}cursor+=n.length}}
 if(at<0)continue;const start=local.positions[at],end=local.positions[at+n.length-1]+1;if(start==null||end==null)continue;ranges.push({start,end,kind,item,index});
 }return ranges.sort((a,b)=>a.start-b.start||({'person':0,'place':1,'official':2,'pinyin':3}[a.kind]-{'person':0,'place':1,'official':2,'pinyin':3}[b.kind]))}
function referenceAge(item,year){const birth=item.link_birth_year;if(item.dates_uncertain||!Number.isInteger(birth)||!Number.isInteger(year)||birth>year||(Number.isInteger(item.link_death_year)&&year>item.link_death_year))return null;const age=year-birth;return age>=0&&age<100?age:null}
function referenceEntity(text,range,p){const {kind,item,index}=range,id=E(p.tongjian_id),label=kind==='pinyin'?displayText(text):referencePronounce(text,p);if(kind==='person'){
 const name=`<button class="entity-name person-name" data-ref-person="${id}:${index}" title="${E(item.people_xingming||item.people_name_jianti_auto||text)}">${label}</button>`,first=referenceFirstMention(p,item),age=first?referenceAge(item,p.year_int):null,life=first&&state.settings.life&&(item.link_birth_year!=null||item.link_death_year!=null||item.link_birth_text||item.link_death_text)?`<sup class="life-label">${item.link_birth_text?E(item.link_birth_text):item.link_birth_year==null?'?':E(referenceShortYear(item.link_birth_year))}—${item.link_death_text?E(item.link_death_text):item.link_death_year==null?'?':E(referenceShortYear(item.link_death_year))}</sup>`:'';
 return (state.settings.age&&age!=null?`<ruby class="person-age">${name}<rt class="age-label" title="按原网站纪年口径计算">${age}岁</rt></ruby>`:name)+life;
 }if(kind==='place')return `<button class="entity-place reference-place" data-ref-place="${id}:${index}" title="${E(item.place_note||'查看地名与相关段落')}">${label}</button>`;
 if(kind==='official')return `<button class="entity-official" data-ref-official="${id}:${index}" title="查看官职释义">${label}</button>`;
 return state.settings.pinyin?`<ruby>${label}<rt>${E(item.pinyin||item.pronunciation||item.py||'')}</rt></ruby>`:label}
const referenceBaseOriginal=renderOriginal;
renderOriginal=function(r){if(!r.reference||!state.settings.reference||!r.tokens)return referenceBaseOriginal(r);const p=r.reference,ranges=referenceRanges(r.o,p);let offset=0,ni=0;return r.tokens.map(t=>{
 if(t.note){const j=ni++;return state.settings.annotations?`<span class="annotation-inline">〔${noteHTML(t)}〕</span>`:`<button class="annotation-label" data-inline-note="${j}" aria-label="查看第${j+1}条胡注">〔注〕</button>`}
 if(t.kind==='image')return `<img class="original-glyph" src="${E(t.src)}" alt="原书异体字形">`;
 const start=offset,text=t.text||'';offset+=text.length;let cursor=0,out='';const contained=ranges.filter(x=>x.start>=start&&x.end<=offset);for(const range of contained){const a=range.start-start,b=range.end-start;if(a<cursor)continue;out+=readingText(text.slice(cursor,a))+referenceEntity(text.slice(a,b),range,p);cursor=b}out+=readingText(text.slice(cursor));if(!contained.length&&t.kind==='name'&&t.personMention!==undefined)return `<button class="entity-name person-name" data-person="${t.personMention}">${displayText(text)}</button>`;if(!contained.length&&t.kind!=='text')return `<span class="entity-${E(t.kind)}">${out}</span>`;return out
 }).join('')};
const referenceRenderContent=renderContent;
renderContent=function(){referenceRenderContent();paintReferenceTools();loadReferenceChapter()};
async function referenceMap(){if(!referenceState.map){const r=await fetch('data/reference-map.json');if(!r.ok)throw Error('目录补充未就绪');referenceState.map=await r.json()}return referenceState.map}
async function loadReferenceChapter(force=false){const stamp=++referenceState.stamp;if(state.book!=='epub2'||!state.settings.reference){referenceStatus.textContent='补充阅读资料';return}const loc=`${state.chapter}:${state.segment}`,local=segments[state.segment];if(local.referenceLoaded&&!force){referenceStatus.textContent='补充资料已载入';return}referenceStatus.textContent='正在补充人物与阅读资料…';try{
 const [map,people]=await Promise.all([referenceMap(),peopleIndex()]);referenceState.names=Object.keys(people.byName);referenceState.profileByQ=new Map(people.profiles.filter(p=>p.qid).map(p=>[p.qid,p]));const entry=map.segments[loc];if(!entry){referenceStatus.textContent='本节暂无补充资料';return}
 if(!referenceState.pending.has(entry.id))referenceState.pending.set(entry.id,referenceAPI('reign',{reign_tongjian_id:entry.id}).catch(e=>{referenceState.pending.delete(entry.id);throw e}));
 const data=await referenceState.pending.get(entry.id);if(stamp!==referenceState.stamp||loc!==`${state.chapter}:${state.segment}`)return;const remote=data.ExtRef_Children_contents||[];let count=0;for(const match of matchReferenceParagraphs(local.paragraphs,remote)){
 const r=local.paragraphs[match.local],p=referenceCorrectParagraph({...remote[match.remote],year_int:data.year_int});r.reference=p;referenceState.paragraphs.set(p.tongjian_id,p);if(!r.t&&p.content_fanyi){r.t=p.content_fanyi;r.translationStatus='reference'}count++}
 local.referenceLoaded=true;local.referenceCount=count;local.referenceTotal=local.paragraphs.length;const y=$('#reading').scrollTop;referenceRenderContent();paintReferenceTools();$('#reading').scrollTop=y;referenceStatus.textContent=`补充资料 ${count}/${local.paragraphs.length} 段`;
 }catch(e){if(stamp===referenceState.stamp){referenceStatus.textContent='补充资料暂不可用 · 点击重试';referenceStatus.title=e.message}}}
function paintReferenceTools(){if(!state.settings.reference)return;document.querySelectorAll('#content .paragraph').forEach(section=>{const r=segments[state.segment].paragraphs[+section.dataset.p],p=r.reference;if(!p)return;const tools=section.querySelector('.paragraph-actions');tools.querySelectorAll('.reference-tool').forEach(x=>x.remove());const id=E(p.tongjian_id);tools.insertAdjacentHTML('beforeend',(p.class_tags||[]).map(t=>`<button class="reference-tool system-tag" data-ref-tag="${E(t)}">${E(t)}</button>`).join('')+(p.ExtRef_Children_topics||[]).map((t,i)=>`<button class="reference-tool topic-tool" data-ref-topic="${id}:${i}">${E(t.title)}</button>`).join('')+`<button class="reference-tool" data-ref-material="${id}">资料${referenceMaterialCount(p)?' '+referenceMaterialCount(p):''}</button>`+(p.zhang_TJZJ_id?`<button class="reference-tool" data-ref-zhang="${E(p.zhang_TJZJ_id)}">张居正直解</button>`:'')+((p.ExtRef_Children_decisions||[]).length?`<button class="reference-tool decision-tool" data-ref-decisions="${id}">决策卡 ${p.ExtRef_Children_decisions.length}</button>`:''));})}
function referenceMaterialCount(p){return (p.background_material_references||[]).length+(p.dtjl_references||[]).length+(p.ExtRef_Children_hu_notes||[]).filter(n=>(n.ExtRef_Children_zhang_notes||[]).length||(n.ExtRef_Children_chenzhu||[]).length).length}
function referenceParts(value){const [id,index]=value.split(':');return {p:referenceState.paragraphs.get(id),index:+index}}
function referenceHTML(html){const doc=new DOMParser().parseFromString(String(html||'').replace(/\\u3000/g,'　'),'text/html');doc.querySelectorAll('script,style,iframe,object,embed').forEach(n=>n.remove());for(const el of [...doc.body.querySelectorAll('*')]){if(!['P','BR','B','STRONG','EM','I','H2','H3','H4','UL','OL','LI','BLOCKQUOTE','TABLE','TR','TD','TH','THEAD','TBODY'].includes(el.tagName)){el.replaceWith(...el.childNodes);continue}for(const a of [...el.attributes])el.removeAttribute(a.name)}return doc.body.innerHTML}
function referenceSource(){return '<p class="search-status">补充资料来源：<a href="https://www.dutongjian.com/" target="_blank" rel="noopener">读通鉴公开阅读资料 ↗</a> · 在线读取公开资料。</p>'}
function referencePaging(page,kind,value){return `<div class="reference-paging"><button data-ref-page="${kind}" data-ref-value="${E(value)}" data-page="${page.current_page-1}" ${page.current_page<=1?'disabled':''}>上一页</button><span>${page.current_page} / ${page.total_pages||1} · 共 ${page.total_paragraphs||0} 段</span><button data-ref-page="${kind}" data-ref-value="${E(value)}" data-page="${page.current_page+1}" ${page.current_page>=page.total_pages?'disabled':''}>下一页</button>${page.anchor_paragraph_order?`<button data-ref-page="${kind}" data-ref-value="${E(value)}" data-page="${Math.ceil(page.anchor_paragraph_order/page.page_size)}">当前出现</button>`:''}</div>`}
// Occurrence API responses contain only the queried entity. Keep the complete
// paragraph (and its entity array ordering) used by existing reading buttons.
function referenceStoreOccurrence(raw){const existing=referenceState.paragraphs.get(raw.tongjian_id);const p=referenceCorrectParagraph(existing?{...raw,...existing}:raw);referenceState.paragraphs.set(p.tongjian_id,p);return p}
function referenceOccurrences(page){return (page.items||[]).map(row=>{const raw=row.paragraph_brief?.paragraph;if(!raw)return '';const p=referenceStoreOccurrence(raw);return `<article class="person-occurrence"><div class="person-occurrence-title"><span>${E(personYear(p.year_int))}</span><button data-ref-jump="${E(p.tongjian_id)}">${E(p.path||'定位到原文')} ↗</button></div><p class="person-snippet">${referencePlainOriginal(p)}</p><details><summary>展开译文与资料</summary><p class="translated">${E(p.content_fanyi||'暂无译文')}</p><button data-ref-material="${E(p.tongjian_id)}">查看段落资料</button></details></article>`}).join('')||'<p class="empty">暂无关联段落</p>'}
async function referencePerson(value,page=1){const {p,index}=referenceParts(value),person=p?.ExtRef_Children_people?.[index];if(!person)return;const stamp=referenceState.dialogStamp+1;openDialog(person.people_name_jianti_auto||person.people_name,'<p>正在载入人物资料…</p>');try{
 if(person.local_profile){await referenceLocalPerson(person.local_profile);return}
 if(person.local_identity){const data=await peopleIndex(),ids=data.byPerson[person.local_identity]||[];const id=ids.find(i=>data.occurrences[i].c===state.chapter&&data.occurrences[i].s===state.segment)??ids[0];if(id!==undefined){await personDialog(id,person.local_identity);return}}
 if(!person.link_td_id){const full=referenceNorm(person.people_xingming||''),data=await peopleIndex(),mention=(data.byName[full]||[]).find(i=>{const m=data.occurrences[i];return m.c===state.chapter&&m.s===state.segment&&segments[state.segment].paragraphs[m.p]?.reference?.tongjian_id===p.tongjian_id});if(mention!==undefined){await personDialog(mention);return}openDialog(person.people_name_jianti_auto||person.people_name,`<p>${E(person.link_td_description||'本条身份尚未确认，请结合上下文辨认。')}</p>${referenceSource()}`);return}
 const d=await referenceAPI('resolved_people_info',{mention_tongjian_id:person.tongjian_id,link_td_id:person.link_td_id,page,page_size:7});if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;const profile=d.profile||{},profileDates=referenceCheckedDates({...person,link_birth_year:profile.birth_year,link_death_year:profile.death_year},p),rel=d.relationships||[],rows=d.occurrence_page||{items:[],current_page:1,total_pages:1};
 $('#dialog').classList.add('person-dialog');$('#dialog-body').innerHTML=`<div class="person-intro"><strong>${E(profile.name||person.people_name)}</strong> <span>${E(referenceProfileLife(profileDates))}</span>${profile.number_id?` <a href="https://wiki.dutongjian.com/id/${encodeURIComponent(profile.number_id)}" target="_blank" rel="noopener">看百科 ↗</a>`:''}<details><summary>${E((profile.biography||person.link_td_description||'暂无简介').slice(0,130))}</summary><p>${E(profile.biography||person.link_td_description||'')}</p></details></div><div class="person-layout"><aside class="person-facts"><h3>人物关系 ${rel.length} 条</h3>${rel.map(r=>`<details class="relationship"><summary>${E((r.relation_property_display_template||'{subject}的'+r.relation_property_label+'是{value}').replace('{subject}',r.source_person_name||'').replace('{value}',r.target_person_name||''))}</summary><p>${E(r.relation_detail||'')}</p>${r.source_person_number_id?`<a href="https://wiki.dutongjian.com/id/${encodeURIComponent(r.source_person_number_id)}" target="_blank" rel="noopener">${E(r.source_person_name)} ↗</a>`:''} ${r.target_person_number_id?`<a href="https://wiki.dutongjian.com/id/${encodeURIComponent(r.target_person_number_id)}" target="_blank" rel="noopener">${E(r.target_person_name)} ↗</a>`:''}</details>`).join('')||'<p>暂无关系记录</p>'}<h3>称呼</h3><p>${E((profile.alias_list||[]).join('、'))}</p>${referenceSource()}<p class="search-status">按本段人物身份编号查询。同名人物分别处理；原资料的简称关联仍须结合上下文核对。</p></aside><section class="person-occurrences">${referencePaging(rows,'person',value)}${referencePersonOccurrences(rows,person,profile)}</section></div>`;
 }catch(e){referenceError(e,()=>referencePerson(value,page))}}
async function referencePlace(value,page=1){const {p,index}=referenceParts(value),place=p?.ExtRef_Children_places?.[index];if(!place)return;const stamp=referenceState.dialogStamp+1;openDialog('地名 · '+place.place_name,'<p>正在载入地名资料…</p>');try{const d=await referenceAPI('resolved_place_info',{place_tongjian_id:place.tongjian_id,page,page_size:10});if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;const profile=d.resolved_profile||{},rows=d.occurrence_page||{items:[],current_page:1,total_pages:1};$('#dialog-body').innerHTML=`<h3>${E(profile.standard_name||d.place_name||place.place_name)}</h3><p>${E(profile.intro||place.place_note||'暂无简介')}</p><p>今地：${E(profile.modern_location||'尚无明确对应')}</p>${profile.lon_min!=null?`<p class="search-status">范围：经度 ${E(profile.lon_min)}–${E(profile.lon_max)}，纬度 ${E(profile.lat_min)}–${E(profile.lat_max)}</p>`:''}${referencePaging(rows,'place',value)}${referenceOccurrences(rows)}${referenceSource()}`;}catch(e){referenceError(e,()=>referencePlace(value,page))}}
function referenceError(e,retry){$('#dialog-body').innerHTML=`<p>${E(e.message)}</p><button class="primary" id="reference-retry">重试</button>${referenceSource()}`;$('#reference-retry').onclick=retry}
async function referenceTopic(value,page=1){const {p,index}=referenceParts(value),topic=p?.ExtRef_Children_topics?.[index];if(!topic)return;const stamp=referenceState.dialogStamp+1;openDialog('主题 · '+topic.title,'<p>正在载入主题…</p>');try{const d=await referenceAPI('topic_info',{topic_tongjian_id:topic.tongjian_id,current_paragraph_tongjian_id:p.tongjian_id,page,page_size:8});if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;$('#dialog-body').innerHTML=`<div class="reference-article">${referenceHTML(d.content)}</div>${(d.children||[]).length?'<h3>子主题</h3>'+d.children.map(t=>`<button class="topic-tool" data-ref-topic-id="${E(t.tongjian_id)}">${E(t.title)}</button>`).join(''):''}${d.occurrence_page?referencePaging(d.occurrence_page,'topic',value)+referenceOccurrences(d.occurrence_page):''}${referenceSource()}`;}catch(e){referenceError(e,()=>referenceTopic(value,page))}}
function referenceMaterial(id){const p=referenceState.paragraphs.get(id);if(!p)return;openDialog('注释与关联资料',`<h3>原文</h3><p class="original">${referencePlainOriginal(p)}</p><details><summary>原网站参考译文</summary><p>${E(p.content_fanyi||'暂无译文')}</p></details><h3>胡三省、章钰及陈垣注释</h3>${(p.ExtRef_Children_hu_notes||[]).map(n=>`<details><summary>${E(n.note_type||'注释')} · ${E((n.note_content||'').slice(0,65))}</summary><p class="annotation-full">${displayText(n.note_content||'')}</p>${(n.ExtRef_Children_zhang_notes||[]).map(v=>`<p>章钰：${E(v.note_content||v.zhang_note_content||v.content||v.text||'')}</p>`).join('')}${(n.ExtRef_Children_chenzhu||[]).map(v=>`<h4>陈垣 · ${E(v.chapter_name)}</h4><p>${E(v.chenzhu_text)}</p>`).join('')}</details>`).join('')||'<p>暂无补充注释</p>'}<h3>关联资料库</h3>${(p.background_material_references||[]).map(b=>`<details><summary>${E(b.display_title||b.path)}</summary>${(b.excerpts||[]).map(e=>`<p>${E(e.context_before)}<mark>${E(e.source_text)}</mark>${E(e.context_after)}</p><button data-ref-passage="${E(e.source_paragraph_tongjian_id)}">阅读全文</button>`).join('')}</details>`).join('')||'<p>暂无关联资料</p>'}<h3>读通鉴论</h3>${(p.dtjl_references||[]).map(d=>`<details><summary>${E(d.title||d.display_title||d.path||'读通鉴论')}</summary>${(d.excerpts||[]).map(x=>`<p>${E(x.context_before)}<mark>${E(x.source_text)}</mark>${E(x.context_after)}</p>`).join('')}<button data-ref-comment-title="${E(d.title)}">在《读通鉴论》中查找全文</button></details>`).join('')||'<p>暂无关联评论</p>'}<h3>官职释义</h3>${(p.ExtRef_Children_officials||[]).map(o=>`<details><summary>${E(o.official_name)} · ${E(o.official_category)}</summary><p>${E(o.official_note)}</p></details>`).join('')||'<p>暂无官职记录</p>'}${(p.reading_annotation_sources||[]).map(s=>`<button data-ref-annotations="${E(id)}" data-source-key="${E(s.source_key||s.key||'')}">${E(s.display_name||s.source_name||s.title||'批读资料')}</button>`).join('')}${referenceSource()}`)}
async function referenceArticle(endpoint,params,title){const stamp=referenceState.dialogStamp+1;openDialog(title,'<p>正在载入…</p>');try{const d=await referenceAPI(endpoint,params);if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;let articles=[];function visit(v){if(Array.isArray(v)){v.forEach(visit);return}if(v&&typeof v==='object'){for(const [k,x]of Object.entries(v)){if(['paragraph_content','content_jianti','content_fanyi','content','text','annotation_content','annotation_text','passage_content','decision_content','description'].includes(k)&&typeof x==='string')articles.push(x);else if(typeof x==='object')visit(x)}}}visit(d);$('#dialog-body').innerHTML=`<div class="reference-article">${[...new Set(articles)].map(referenceHTML).join('<hr>')||'<p>本条资料没有可显示的正文。</p>'}</div>${referenceSource()}`;}catch(e){referenceError(e,()=>referenceArticle(endpoint,params,title))}}
async function referenceJump(id){const p=referenceState.paragraphs.get(id);if(!p)return;try{const [map,locator]=await Promise.all([referenceMap(),referenceAPI('paragraph_locator',{ref:id})]);const target=map.reverse[locator.reign_tongjian_id];if(!target)throw Error('未找到本地对应章节');$('#dialog').close();await navigate('epub2',target.chapter,target.segment,0);const a=referenceNorm(p.content),rows=segments[state.segment].paragraphs;let best=0,score=0;rows.forEach((r,i)=>{const q=referenceScore(referenceNorm(r.o),a);if(q>score){best=i;score=q}});if(score<.7){toast('已定位年份，请结合原文寻找对应段落');return}jumpTo(best);history.replaceState(null,'','#'+key(best));}catch(e){toast(e.message)}}
function referenceOverview(){const seg=segments[state.segment],count=seg?.referenceCount;openDialog('补充阅读资料',`<p>人物年龄、生卒年、亲属关系、地名、官职、主题、系统标签和关联注释，按当前章节从原网站公开阅读资料取得。</p><p>首次访问需要联网，已访问资料保存在本机；EPUB 原文、书签和个人批注仍使用本地内容。</p>${count!=null?`<p>当前 ${count}/${seg.referenceTotal} 段已匹配。</p>`:''}<div class="reading-checks"><label><input id="reference-enabled" type="checkbox" ${state.settings.reference?'checked':''}>显示补充阅读资料</label></div><button id="reference-load" class="primary">重新载入本节资料</button><h3>功能对照</h3><p>正文阅读、文白联动、人物及地名查询、官职释义、主题与关联资料均可在当前页使用。沙盘态势已加入地图标绘、记录、自动保存和导入导出；账号同步、AI问答和古本影像仍需独立接入。</p><p><a href="comparison.html" target="_blank" rel="noopener">查看逐项对照清单 ↗</a></p>${referenceSource()}`);$('#reference-enabled').onchange=e=>{state.settings.reference=e.target.checked;persist();redrawReading()};$('#reference-load').onclick=()=>{$('#dialog').close();loadReferenceChapter(true)}}
actions.reference=referenceOverview;
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;let handled=true;if(el.dataset.refPerson)referencePerson(el.dataset.refPerson);else if(el.dataset.refPlace)referencePlace(el.dataset.refPlace);else if(el.dataset.refOfficial){const {p,index}=referenceParts(el.dataset.refOfficial),o=p?.ExtRef_Children_officials?.[index];if(o)openDialog('官职 · '+o.official_name,`<p>${E(o.official_category)} · ${E(o.official_rank||'')}</p><p>${E(o.official_note)}</p>${referenceSource()}`)}else if(el.dataset.refMaterial)referenceMaterial(el.dataset.refMaterial);else if(el.dataset.refTopic)referenceTopic(el.dataset.refTopic);else if(el.dataset.refTopicId){const p={tongjian_id:'topic-'+el.dataset.refTopicId,ExtRef_Children_topics:[{tongjian_id:el.dataset.refTopicId,title:el.textContent}]};referenceState.paragraphs.set(p.tongjian_id,p);referenceTopic(p.tongjian_id+':0')}else if(el.dataset.refPage){const fn={person:referencePerson,place:referencePlace,topic:referenceTopic,tag:referenceTag}[el.dataset.refPage];fn?.(el.dataset.refValue,+el.dataset.page)}else if(el.dataset.refJump)referenceJump(el.dataset.refJump);else if(el.dataset.refZhang)referenceArticle('zhang_tjzj_detail',{zhang_tjzj_id:el.dataset.refZhang},'张居正 · 资治通鉴直解');else if(el.dataset.refCommentTitle)referenceFindComment(el.dataset.refCommentTitle);else if(el.dataset.refDecisionId)referenceDecision(el.dataset.refDecisionId);else if(el.dataset.refPassage)referencePassage({tongjian_id:el.dataset.refPassage});else if(el.dataset.refAnnotations)referenceArticle('reading_annotations',{target_id:el.dataset.refAnnotations,source_key:el.dataset.sourceKey},el.textContent);else if(el.dataset.refDecisions){const p=referenceState.paragraphs.get(el.dataset.refDecisions);openDialog('决策卡',`<p>${E(segments[state.segment].title)}</p>${(p?.ExtRef_Children_decisions||[]).map(d=>`<details><summary>${E(d.decision_name||d.title||d.decision_title||d.name||'历史决策')}</summary><button data-ref-decision-id="${E(d.decision_tongjian_id||d.tongjian_id)}">查看选项与历史结果</button></details>`).join('')}${referenceSource()}`)}else if(el.dataset.refTag)referenceTag(el.dataset.refTag);else handled=false;if(handled){e.preventDefault();e.stopImmediatePropagation()}},true);
const backupTools=document.createElement('div');backupTools.className='reference-resource-tools';backupTools.innerHTML='<button data-action="reference">人物与补充资料</button><button data-action="lexicon">字词查询</button><button data-action="backup">导出／导入阅读记录</button><a href="comparison.html" target="_blank" rel="noopener">功能对照说明 ↗</a><a href="person-audit.html" target="_blank" rel="noopener">人物核查记录 ↗</a>';$('#tools .tool-body').append(backupTools);
actions.lexicon=()=>{openDialog('字词查询','<form id="lexicon-form" class="row"><input id="lexicon-query" aria-label="查询字词" placeholder="输入字词，如：縯、大司徒"><button class="primary">查询</button></form><div id="lexicon-result"></div>');$('#lexicon-form').onsubmit=async e=>{e.preventDefault();const q=$('#lexicon-query').value.trim(),result=$('#lexicon-result');if(!q)return;result.textContent='正在查询…';try{const d=await referenceAPI('lexicon/lookup',{query:q});if(!result.isConnected||$('#lexicon-query')?.value.trim()!==q)return;const entries=d.entries||d.entry_list||[];result.innerHTML=entries.map(v=>`<h3>${E(v.headword||v.word||q)}</h3>${referenceHTML(v.content||v.definition||v.text||'')}`).join('')||'<p>暂无词条，可查阅胡注或通鉴百科。</p>'}catch(e){if(result.isConnected)result.textContent=e.message}}};
function mergeReadingBackup(text){const d=JSON.parse(text);if(d.format!=='tongjian-reader-backup'||!d.saved)throw Error('请选择本阅读器导出的记录');for(const type of ['bookmarks','notes','last'])for(const [k,v]of Object.entries(d.saved[type]||{}))if(v&&typeof v==='object'&&(!state[type][k]||(v.date||0)>(state[type][k].date||0)))state[type][k]=v;for(const [k,v]of Object.entries(d.saved.tags||{}))if(Array.isArray(v))state.tags[k]=[...new Set([...(state.tags[k]||[]),...v.filter(t=>typeof t==='string')])];for(const [k,v]of Object.entries(d.saved.settings||{}))if(Object.hasOwn(state.settings,k)&&typeof v===typeof state.settings[k]&&(typeof v!=='number'||Number.isFinite(v)))state.settings[k]=v;state.visited={...state.visited,...d.saved.visited};state.seconds=Math.max(state.seconds,Number(d.saved.seconds)||0);persist();$('#dialog').close();redrawReading();toast('阅读记录已合并')}
actions.backup=()=>{openDialog('阅读记录备份','<p>将书签、批注、标签、设置和进度保存成文件，可在另一台电脑导入。</p><button id="export-reading" class="primary">导出阅读记录</button><p><label>导入阅读记录 <input id="import-reading" type="file" accept=".json"></label></p><details id="backup-text-details"><summary>文本备份与导入（浏览器无法下载时使用）</summary><p>导出后可复制下方完整内容保存；也可粘贴已有备份，再点击导入。</p><textarea id="backup-text" aria-label="阅读记录备份内容" rows="8" style="width:100%;font-family:monospace"></textarea><button id="import-reading-text">导入粘贴的备份</button></details><p class="search-status">导入按记录时间合并，不删除当前书签与批注；阅读设置采用备份值。</p>');$('#export-reading').onclick=()=>{persist();const text=JSON.stringify({format:'tongjian-reader-backup',version:1,saved:JSON.parse(localStorage.getItem(KEY))},null,2);$('#backup-text').value=text;$('#backup-text-details').open=true;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download='通鉴阅读记录-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);toast('备份已生成，可下载或复制文本保存')};$('#import-reading').onchange=async e=>{try{if(e.target.files[0])mergeReadingBackup(await e.target.files[0].text())}catch(e){toast(e.message)}};$('#import-reading-text').onclick=()=>{try{mergeReadingBackup($('#backup-text').value)}catch(e){toast(e.message)}}};

if(segments[state.segment])renderContent();
function referenceIdentityConflict(text,item,profile=null){const short=referenceNorm(item.people_name||''),full=referenceNorm(profile?.name||item.people_xingming||(item.link_td_description||'').split(/[，,。；;]/)[0]);if(!short||short.length>2||full.length<=short.length||!full.endsWith(short)||referenceNorm(text).includes(full))return false;if(!referenceState.suffixes.has(short))referenceState.suffixes.set(short,referenceState.names.filter(n=>n.length>short.length&&n.length<=4&&n.endsWith(short)));return referenceState.suffixes.get(short).some(n=>n!==full&&referenceNorm(text.slice(0,140)).includes(n))}
function referencePronounce(text,p){if(!state.settings.pinyin)return displayText(text);let cursor=0,out='';const matches=(p.ExtRef_Children_pinyin||[]).filter(x=>x.text&&text.includes(x.text));for(const m of matches){const at=text.indexOf(m.text,cursor);if(at<0)continue;out+=displayText(text.slice(cursor,at))+`<ruby>${displayText(m.text)}<rt>${E(m.pinyin||'')}</rt></ruby>`;cursor=at+m.text.length}return out+displayText(text.slice(cursor))}
function referencePlainOriginal(p){const text=String(p.content||'').replace(/^\d+/,''),ranges=referenceRanges(text,p);let cursor=0,out='';for(const r of ranges){if(r.start<cursor)continue;out+=readingText(text.slice(cursor,r.start))+referenceEntity(text.slice(r.start,r.end),r,p);cursor=r.end}return out+readingText(text.slice(cursor))}
function referencePersonOccurrences(page,person,profile){let hidden=0;const items=(page.items||[]).filter(row=>{const raw=row.paragraph_brief?.paragraph,p=raw?referenceCorrectParagraph(raw):null;const names=(p?.ExtRef_Children_people||[]).filter(x=>x.link_td_id===person.link_td_id);const lostIdentity=raw?.ExtRef_Children_people?.some(x=>x.link_td_id===person.link_td_id)&&!names.length;const conflict=lostIdentity||names.length&&names.every(x=>referenceIdentityConflict(p.content,x,profile));if(conflict)hidden++;return !conflict});return (hidden?`<p class="search-status">本页有 ${hidden} 条简称疑似混同，已暂时隐藏。</p>`:'')+referenceOccurrences({...page,items})}
async function referenceDecision(id){const stamp=referenceState.dialogStamp+1;openDialog('历史决策','<p>正在载入…</p>');try{const rows=await referenceAPI('decisions',{decision_tongjian_id:id,limit:1});if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;const d=rows[0];if(!d)throw Error('暂无决策资料');$('#dialog-title').textContent=d.decision_name;$('#dialog-body').innerHTML=`<p>${E(d.role_name)} · ${E(personYear(d.year_int))}</p><p>${E(d.background)}</p>${(d.detail?.options||[]).map((o,i)=>`<details><summary>选项 ${i+1}：${E(o.choice)}</summary><p>支持理由：${E(o.support_point)}</p><p>反对理由：${E(o.oppose_point)}</p></details>`).join('')}<details><summary>查看历史选择</summary><p>${E(d.detail?.final_choice||'暂无记录')}</p></details>${referenceSource()}`;}catch(e){referenceError(e,()=>referenceDecision(id))}}
async function referenceFindComment(title){const phrase=referenceNorm(title.replace(/^[一二三四五六七八九十百\d]+\s*/,''));const b=state.books.find(b=>b.id==='lun');let candidates=[];for(let c=0;c<b.chapters.length;c++)for(let s=0;s<b.chapters[c].segments.length;s++){const t=referenceNorm(b.chapters[c].segments[s]);if(t.includes(phrase)||phrase.includes(t)&&t.length>3)candidates.push({book:'lun',chapter:c,segment:s,paragraph:0,title:b.chapters[c].segments[s]})}if(candidates.length){openDialog('读通鉴论 · '+title,candidates.map(r=>`<button class="result" data-location="${E(JSON.stringify(r))}">${E(r.title)}</button>`).join(''));return}searchDialog(phrase.slice(0,12));}
async function referenceTag(tag,page=1){const stamp=referenceState.dialogStamp+1;openDialog('系统标签 · '+tag,'<p>正在查找全书关联段落…</p>');try{const d=await referenceAPI('class_tag_info',{tag_value:tag,page,page_size:8});if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;const rows=d.occurrence_page;$('#dialog-body').innerHTML=`<p>${E(d.description||d.tag_description||'全书同类历史事件与段落')}</p>${rows?referencePaging(rows,'tag',tag)+referenceOccurrences(rows):'<p>暂无相关段落</p>'}${referenceSource()}`;}catch(e){referenceError(e,()=>referenceTag(tag,page))}}
let atlasData=null,atlasStamp=0;
async function atlasDialog(){if(!atlasData){const r=await fetch('data/atlas.json');atlasData=await r.json()}const map=await referenceMap(),year=map.segments[`${state.chapter}:${state.segment}`]?.year;let index=atlasData.findIndex(x=>year>=x.start_year_int&&year<=x.end_year_int);if(index<0)index=0;openDialog('历史地图',`<div class="atlas-controls"><select id="atlas-period" aria-label="地图时代">${atlasData.map((p,i)=>`<option value="${i}" ${i===index?'selected':''}>${E(p.name)}</option>`).join('')}</select><select id="atlas-sheet" aria-label="地图名称"></select><button id="atlas-minus" aria-label="缩小地图">−</button><button id="atlas-plus" aria-label="放大地图">＋</button><span id="atlas-zoom">100%</span></div><p id="atlas-status" class="search-status">请选择地图</p><div class="atlas-canvas"><img id="atlas-image" alt="历史地图" hidden></div><p class="search-status">图片来源：原网站历史地图；放大后可滚动查看。首次查看需要联网。</p>`);$('#dialog').classList.add('atlas-dialog');let zoom=100;const changeZoom=n=>{zoom=Math.max(50,Math.min(400,n));$('#atlas-image').style.width=zoom+'%';$('#atlas-zoom').textContent=zoom+'%'};const loadSheet=async()=>{const group=atlasData[+$('#atlas-period').value],item=group.items[+$('#atlas-sheet').value],stamp=++atlasStamp;$('#atlas-status').textContent='正在载入 '+item.title+'…';$('#atlas-image').hidden=true;try{const d=await referenceAPI('map/image-url',{oss_filename:item.oss_filename});if(stamp!==atlasStamp||!$('#atlas-image'))return;const image=$('#atlas-image');image.onload=()=>{if(stamp===atlasStamp){image.hidden=false;$('#atlas-status').textContent=item.title}};image.onerror=()=>{if(stamp===atlasStamp)$('#atlas-status').textContent='地图暂时无法载入，请重新选择或稍后重试。'};image.alt=item.title;image.src=d.image_url;changeZoom(100)}catch(e){if(stamp===atlasStamp&&$('#atlas-status'))$('#atlas-status').textContent=e.message}};const loadGroup=()=>{const group=atlasData[+$('#atlas-period').value];$('#atlas-sheet').innerHTML=group.items.map((x,i)=>`<option value="${i}">${E(x.title)}</option>`).join('');loadSheet()};$('#atlas-period').onchange=loadGroup;$('#atlas-sheet').onchange=loadSheet;$('#atlas-minus').onclick=()=>changeZoom(zoom-25);$('#atlas-plus').onclick=()=>changeZoom(zoom+25);loadGroup()}
actions.atlas=atlasDialog;
async function climateDialog(){const r=await fetch('data/climate.json'),data=await r.json(),map=await referenceMap(),year=map.segments[`${state.chapter}:${state.segment}`]?.year||1;openDialog('历史气候',`<p>当前纪年：${E(personYear(year))}</p><div class="row"><button id="climate-current" class="primary">当前年代附近</button><button id="climate-all">近五千年</button></div><div id="climate-chart"></div><p id="climate-value" class="climate-value"></p><p class="search-status">竺可桢近五千年气候研究的原网站整理曲线，按十年采样；纵轴为温度变化（℃），带有年代和温度误差，不等同于逐年观测。</p><a href="https://www.dutongjian.com/historical-climate/%E4%B8%AD%E5%9B%BD%E8%BF%91%E4%BA%94%E5%8D%83%E5%B9%B4%E6%9D%A5%E6%B0%94%E5%80%99%E5%8F%98%E8%BF%81%E7%9A%84%E5%88%9D%E6%AD%A5%E7%A0%94%E7%A9%B6.md" target="_blank" rel="noopener">阅读原网站收录的研究原文 ↗</a>`);const draw=all=>{const rows=data.filter(x=>all||Math.abs(x.year-year)<=500),min=rows[0].year,max=rows.at(-1).year,w=880,h=340,left=60,top=25,x=t=>left+(t-min)/(max-min)*(w-left-30),y=t=>top+(3.2-t)/5*(h-top-45);const nearest=rows.reduce((a,b)=>Math.abs(b.year-year)<Math.abs(a.year-year)?b:a);$('#climate-chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="历史气候温度变化曲线">${[-1,0,1,2,3].map(t=>`<line x1="${left}" y1="${y(t)}" x2="${w-30}" y2="${y(t)}" stroke="#dbe3ed"/><text x="12" y="${y(t)+5}">${t}℃</text>`).join('')}${Array.from({length:6},(_,i)=>min+(max-min)*i/5).map(t=>`<text x="${x(t)}" y="${h-12}" text-anchor="middle">${t<0?'前'+Math.round(-t):Math.round(t)}年</text>`).join('')}<polyline fill="none" stroke="#368cce" stroke-width="3" points="${rows.map(d=>x(d.year)+','+y(d.temperature)).join(' ')}"/><line x1="${x(nearest.year)}" y1="${top}" x2="${x(nearest.year)}" y2="${h-45}" stroke="#d7a24b" stroke-dasharray="5 4"/>${rows.map((d,i)=>`<circle data-climate-point="${i}" cx="${x(d.year)}" cy="${y(d.temperature)}" r="5" fill="${d===nearest?'#e4a13b':'transparent'}" tabindex="0"><title>${E(personYear(d.year))}：${d.temperature.toFixed(2)}℃</title></circle>`).join('')}</svg>`;const show=d=>$('#climate-value').textContent=`${personYear(d.year)} · ${d.period} · 温度变化 ${d.temperature.toFixed(2)}℃（±${d.temperatureError}℃；年代误差约±${d.yearError}年）`;show(nearest);$('#climate-chart').querySelectorAll('[data-climate-point]').forEach(el=>{el.onpointerenter=el.onfocus=()=>show(rows[+el.dataset.climatePoint])})};$('#climate-current').onclick=()=>draw(false);$('#climate-all').onclick=()=>draw(true);draw(false)}
actions.climate=climateDialog;
const geographyTools=document.createElement('div');geographyTools.className='reference-resource-tools';geographyTools.innerHTML='<button data-action="atlas">历史地图</button><button data-action="climate">历史气候</button>';$('#tools .tool-body').append(geographyTools);
const geographyButtons=document.createElement('span');geographyButtons.className='geography-buttons';geographyButtons.innerHTML='<button data-action="atlas" aria-label="打开历史地图" title="历史地图">▧</button><button data-action="climate" aria-label="打开历史气候" title="历史气候">☀</button>';$('.breadcrumb > div').append(geographyButtons);
const originalOpenDialog=openDialog;openDialog=function(title,html){$('#dialog').classList.remove('atlas-dialog');++referenceState.dialogStamp;return originalOpenDialog(title,html)};
function referenceFirstMention(p,item){const who=item.link_td_id;if(!who)return true;const first=(p.ExtRef_Children_people||[]).filter(x=>x.link_td_id===who).reduce((a,b)=>b.start_index<a.start_index?b:a,item);return first===item}
function referenceShortYear(year){return year<0?'前'+(-year):String(year)}
async function referenceLocalPerson(identity){const stamp=referenceState.dialogStamp+1;openDialog('刘恭 · 赤眉时期','<p>正在载入校订人物资料…</p>');try{const data=await peopleIndex();const mentions=(data.byName['刘恭']||[]).map(i=>data.occurrences[i]).filter(x=>x.y>=23&&x.y<=30);mentions.push({c:43,s:1,p:14,y:25});const rows=[...new Map(mentions.map(x=>[`${x.c}:${x.s}:${x.p}`,x])).values()].sort((a,b)=>a.y-b.y||a.c-b.c||a.s-b.s||a.p-b.p);const chapters=await Promise.all(rows.map(x=>peopleChapter(x.c)));if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;$('#dialog').classList.add('person-dialog');$('#dialog-body').innerHTML=`<div class="person-intro"><strong>刘恭</strong><span> 生卒年不详</span><p>刘盆子的兄长。曾受赤眉派遣向光武帝请求投降，后为更始帝报仇，杀谢禄并自系狱，获赦。</p></div><div class="person-layout"><aside class="person-facts"><h3>人物关系</h3><p>刘盆子是刘恭的弟弟。</p><p class="search-status">本段原资料误用了刘盆子的人物编号，现已分开。没有可靠出生年，不显示年龄。</p><h3>依据</h3><p>本书 26 年正文写“密教弟盆子”，刘恭称“恭弟”；27 年正文记乞降及杀谢禄。下方段落可返回原文核对。</p></aside><section class="person-occurrences"><h3>相关段落 ${rows.length} 段</h3>${rows.map((r,i)=>{const p=chapters[i][r.s].paragraphs[r.p];return `<article class="person-occurrence"><div class="person-occurrence-title"><span>${E(personYear(r.y))}</span><button data-location="${E(JSON.stringify({book:'epub2',chapter:r.c,segment:r.s,paragraph:r.p}))}">${E(state.books.find(b=>b.id==='epub2').chapters[r.c].title)} / 第${r.p+1}段 ↗</button></div><p class="person-snippet">${personExcerpt(p.o,['刘恭','劉恭'])}</p><details><summary>展开译文</summary><p class="translated">${E(p.t||'暂无译文')}</p></details></article>`}).join('')}</section></div>`}catch(e){referenceError(e,()=>referenceLocalPerson(identity))}}
const selectionTools=document.createElement('div');selectionTools.className='selection-tools';selectionTools.hidden=true;selectionTools.innerHTML='<button data-selection-action="lexicon">字词</button><button data-selection-action="note">写批注</button><button data-selection-action="materials">资料</button><button data-selection-action="copy">复制</button>';document.body.append(selectionTools);let readingSelection=null;
$('#content').addEventListener('pointerup',()=>setTimeout(()=>{const selection=window.getSelection();if(!selection||selection.isCollapsed){selectionTools.hidden=true;return}const element=selection.anchorNode?.parentElement,paragraph=element?.closest('.paragraph');if(!paragraph){selectionTools.hidden=true;return}const p=+paragraph.dataset.p,text=captureReadingQuote(segments[state.segment].paragraphs[p].o)||selection.toString().trim();if(!text||text.length>500){selectionTools.hidden=true;return}const range=selection.getRangeAt(0).getBoundingClientRect();readingSelection={p,text};selectionTools.hidden=false;selectionTools.style.left=Math.max(8,Math.min(innerWidth-selectionTools.offsetWidth-8,range.left))+'px';selectionTools.style.top=Math.max(8,range.top-selectionTools.offsetHeight-9)+'px'},0));
selectionTools.addEventListener('pointerdown',e=>e.preventDefault());selectionTools.addEventListener('click',e=>{const action=e.target.closest('[data-selection-action]')?.dataset.selectionAction;if(!action||!readingSelection)return;const {p,text}=readingSelection;selectionTools.hidden=true;if(action==='note')paragraphDialog(p);if(action==='materials'){const r=segments[state.segment].paragraphs[p];if(r.reference)referenceMaterial(r.reference.tongjian_id);else paragraphDialog(p)}if(action==='lexicon'){actions.lexicon();$('#lexicon-query').value=text;$('#lexicon-form').requestSubmit()}if(action==='copy')navigator.clipboard?.writeText(text).then(()=>toast('选文已复制')).catch(()=>toast('请使用复制快捷键'));});
$('#reading').addEventListener('scroll',()=>selectionTools.hidden=true,{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')selectionTools.hidden=true});

// The public resource library has its own book directory and pagination.
async function referenceLibrary(){const stamp=referenceState.dialogStamp+1;openDialog('史料资料库','<p>正在载入书目…</p>');try{const d=await referenceAPI('background-materials/books');if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;$('#dialog-body').innerHTML=`<form id="library-search" class="row"><input id="library-query" aria-label="搜索史料" placeholder="搜索二十四史、容斋随笔"><button class="primary">搜索</button></form>${(d.categories||[]).map(c=>`<h3>${E(c.category)}</h3><div class="library-books">${c.books.map(b=>`<button data-library-book="${E(b.name)}">${E(b.name)}</button>`).join('')}</div>`).join('')}${referenceSource()}`;$('#library-search').onsubmit=e=>{e.preventDefault();referenceLibrarySearch($('#library-query').value.trim())}}catch(e){referenceError(e,referenceLibrary)}}
async function referenceLibraryToc(name){const stamp=referenceState.dialogStamp+1;openDialog('资料目录 · '+name,'<p>正在载入目录…</p>');try{const d=await referenceAPI('background-materials/toc',{name});if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;const tree=rows=>rows.map(x=>(x.children||[]).length?`<details><summary>${E(x.label)}</summary>${tree(x.children)}</details>`:`<p><button data-ref-passage="${E(x.tongjian_id)}">${E(x.label)}</button></p>`).join('');$('#dialog-body').innerHTML=`<button data-library-home>全部书目</button><div class="library-toc">${tree(d.tree||[])}</div>${referenceSource()}`}catch(e){referenceError(e,()=>referenceLibraryToc(name))}}
async function referencePassage(params){const stamp=referenceState.dialogStamp+1;openDialog('资料库全文','<p>正在载入全文…</p>');try{const d=await referenceAPI('background-materials/passage',params);if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;$('#dialog-title').textContent='资料库 · '+d.name;$('#dialog-body').innerHTML=`<div class="reference-paging"><button data-library-book="${E(d.name)}">书目目录</button><button data-library-name="${E(d.name)}" data-library-page="${d.page-1}" ${d.page<=1?'disabled':''}>上一页</button><span>${d.page}/${d.total_pages} · 共${d.total}段</span><button data-library-name="${E(d.name)}" data-library-page="${d.page+1}" ${d.page>=d.total_pages?'disabled':''}>下一页</button></div><div class="reference-article">${(d.passages||[]).map(p=>`<article id="material-${E(p.tongjian_id)}" ${p.tongjian_id===d.anchor_id?'class="material-anchor"':''}><h3>${E(p.path)}</h3><p>${E(p.content_jianti||p.content||'')}</p>${p.content_fanyi?`<p class="translated">${E(p.content_fanyi)}</p>`:''}${(p.zztj_links||[]).map(l=>`<button data-library-link="${E(l.target_paragraph_tongjian_id||l.paragraph_tongjian_id||'')}">${E(l.target_path||'查看通鉴关联段落')}</button>`).join('')}</article>`).join('')}</div>${referenceSource()}`;if(params.tongjian_id)document.getElementById('material-'+d.anchor_id)?.scrollIntoView({block:'start'})}catch(e){referenceError(e,()=>referencePassage(params))}}
async function referenceLibrarySearch(query,page=1){if(!query)return;const stamp=referenceState.dialogStamp+1;openDialog('史料搜索 · '+query,'<p>正在查找…</p>');try{const d=await referenceAPI('background-materials/search',{query,page,page_size:10});if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;const rows=d.items||d.results||d.passages||[];$('#dialog-body').innerHTML=`<button data-library-home>全部书目</button><p>共 ${d.total||0} 条</p>${rows.map(p=>`<article class="person-occurrence"><button data-ref-passage="${E(p.tongjian_id||p.id)}">${E(p.name)} · ${E(p.path)}</button><p>${referenceHTML(p.content_jianti||p.content||p.snippet||'')}</p></article>`).join('')||'<p>暂无结果</p>'}<div class="reference-paging"><button data-library-query="${E(query)}" data-library-search-page="${page-1}" ${page<=1?'disabled':''}>上一页</button><span>${page}/${d.total_pages||Math.max(1,Math.ceil((d.total||0)/10))}</span><button data-library-query="${E(query)}" data-library-search-page="${page+1}" ${page*10>=(d.total||0)?'disabled':''}>下一页</button></div>${referenceSource()}`}catch(e){referenceError(e,()=>referenceLibrarySearch(query,page))}}
actions.library=referenceLibrary;const libraryButton=document.createElement('button');libraryButton.dataset.action='library';libraryButton.textContent='史料资料库 · 二十四史';backupTools.append(libraryButton);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.libraryBook)referenceLibraryToc(b.dataset.libraryBook);else if(b.dataset.libraryPage)referencePassage({name:b.dataset.libraryName,page:b.dataset.libraryPage});else if(b.dataset.libraryQuery)referenceLibrarySearch(b.dataset.libraryQuery,+b.dataset.librarySearchPage);else if(b.hasAttribute('data-library-home'))referenceLibrary();else if(b.dataset.libraryLink){const id=b.dataset.libraryLink;referenceAPI('brief',{tongjian_id:id,type:'paragraph'}).then(d=>{const p=d.paragraph||d;if(p.content){referenceState.paragraphs.set(id,p);referenceJump(id)}else toast('暂未找到关联原文')}).catch(e=>toast(e.message))}});
async function officialsDialog(){openDialog('历代官制','<div class="row"><select id="officials-dynasty" aria-label="官制时代">'+[['zhou','周'],['qin','秦'],['xihan','西汉'],['donghan','东汉'],['sanguo','三国'],['xijin','西晋'],['dongjin','东晋十六国'],['nanbeichao','南北朝'],['sui','隋'],['tang','唐'],['wudaishiguo','五代十国']].map(([id,name])=>`<option value="${id}">${name}</option>`).join('')+'</select><input id="officials-filter" aria-label="筛选官职" placeholder="查找官职或机构"></div><div id="officials-tree"></div>');const box=$('#officials-tree'),select=$('#officials-dynasty');let data=null;const draw=()=>{if(!data||!box.isConnected)return;const q=$('#officials-filter').value.trim();function node(n){const kids=(n.children||[]).map(node).join(''),self=!q||[n.name,n.description,JSON.stringify(n.details||{})].join('').includes(q);if(!self&&!kids)return '';return `<details class="official-node" ${q?'open':''}><summary>${E(n.name)}</summary><p>${E(n.description||'')}</p>${Object.entries(n.details||{}).map(([k,v])=>`<p>${E(typeof v==='string'?v:JSON.stringify(v))}</p>`).join('')}<div>${kids}</div></details>`}box.innerHTML=`<h3>${E(data.title)}</h3><p>${E(data.meta?.period||'')}</p>${(data.meta?.notes||[]).map(n=>`<p>${E(n)}</p>`).join('')}${node(data.root)||'<p>没有找到匹配的官职</p>'}${referenceSource()}`};select.onchange=async()=>{const value=select.value;box.textContent='正在载入…';try{const r=await fetch('data/officials/'+value+'.json');const d=await r.json();if(!box.isConnected||select.value!==value)return;data=d;draw()}catch(e){if(box.isConnected)box.textContent='官制资料暂时无法载入'}};$('#officials-filter').oninput=draw;select.onchange()}
actions.officials=officialsDialog;const officialsButton=document.createElement('button');officialsButton.dataset.action='officials';officialsButton.textContent='历代官制 · 机构与品阶';backupTools.append(officialsButton);
