/* Clause linking preserves names, annotations and saved selections. */
'use strict';
if(!state.settings.sentenceLayoutV1){state.settings.parallel=true;state.settings.translation=true;state.settings.sentenceLayoutV1=true;persist()}
const sentenceLinks=new WeakMap();
let activeSentence=null;
let entityPaint=0;
let hoveredReadingEntity=null;
const sentenceTip=document.createElement('div');sentenceTip.className='sentence-tip';sentenceTip.id='sentence-tip';sentenceTip.setAttribute('role','status');sentenceTip.hidden=true;document.body.append(sentenceTip);
function readingClauses(text){const out=[];const pattern=/[^，,。！？!?；;：:]+[，,。！？!?；;：:]?[”」』]?|[，,。！？!?；;：:]/g;let m;while((m=pattern.exec(text)))out.push({text:m[0],start:m.index,end:m.index+m[0].length});return out}
function clauseSimilarity(a,b){const clean=s=>[...toSimple(s).replace(/[^\p{Script=Han}\d]/gu,'')];const aa=clean(a),bb=clean(b),bs=new Set(bb);if(!aa.length||!bb.length)return 0;const shared=aa.filter(c=>bs.has(c)).length;return shared/Math.max(aa.length,bb.length)}
function linkReadingClauses(original,translated){const n=original.length,m=translated.length;if(!n||!m)return [];const dp=Array.from({length:n+1},()=>Array(m+1).fill(Infinity)),prev=Array.from({length:n+1},()=>Array(m+1));dp[0][0]=0;for(let i=0;i<=n;i++)for(let j=0;j<=m;j++){if(!Number.isFinite(dp[i][j]))continue;for(const [a,b] of [[1,1],[1,2],[2,1],[1,3],[3,1]]){if(i+a>n||j+b>m)continue;const x=original.slice(i,i+a).map(x=>x.text).join(''),y=translated.slice(j,j+b).map(x=>x.text).join('');const similarity=clauseSimilarity(x,y);const ratio=Math.abs(Math.log((y.length+2)/(x.length+2)/1.35));const relative=Math.abs((i+a/2)/n-(j+b/2)/m);const cost=(1-similarity+.24*ratio+.6*relative)*(a+b)/2+.28*(a+b-2);if(dp[i][j]+cost<dp[i+a][j+b]){dp[i+a][j+b]=dp[i][j]+cost;prev[i+a][j+b]={i,j,a,b}}}}const links=[];let i=n,j=m;while(i||j){const p=prev[i][j];if(!p)return [{from:original.map((_,i)=>i),to:translated.map((_,i)=>i),approximate:true}];const from=Array.from({length:p.a},(_,k)=>p.i+k),to=Array.from({length:p.b},(_,k)=>p.j+k);const x=from.map(k=>original[k].text).join(''),y=to.map(k=>translated[k].text).join('');links.unshift({from,to,approximate:clauseSimilarity(x,y)<.18});i=p.i;j=p.j}return links}
function sentenceTextNodes(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];let node,text='';while(node=walker.nextNode()){if(node.parentElement.closest('rt,.annotation-inline,.annotation-label,.life-label'))continue;nodes.push({node,start:text.length,end:text.length+node.length});text+=node.textContent}return {nodes,text}}
function wrapReadingClauses(root){const {nodes,text}=sentenceTextNodes(root),clauses=readingClauses(text);for(const entry of nodes){const matches=clauses.map((clause,id)=>({id,start:Math.max(0,clause.start-entry.start),end:Math.min(entry.node.length,clause.end-entry.start)})).filter(x=>x.end>x.start);for(const match of matches.reverse()){const part=entry.node.splitText(match.start);part.splitText(match.end-match.start);const span=document.createElement('span');span.className='reading-clause';span.dataset.sentenceId=match.id;part.before(span);span.append(part)}}return clauses}
function prepareSentenceLinks(){clearSentenceLink();hoveredReadingEntity=null;clearEntityHighlight();document.querySelectorAll("#content .original .entity-place").forEach(el=>{el.tabIndex=0;el.setAttribute("role","button");el.setAttribute("aria-label","标记地名 "+el.textContent);el.title="悬停标记同名地点"});document.querySelectorAll('#content .texts').forEach(group=>{const original=group.querySelector('.original'),translated=group.querySelector('.translated');if(!original||!translated)return;const a=wrapReadingClauses(original),b=wrapReadingClauses(translated);sentenceLinks.set(group,{original:a,translated:b,links:linkReadingClauses(a,b)});original.setAttribute('aria-label','原文，点击句子查看对应译文');translated.setAttribute('aria-label','译文，点击句子联动原文')})}
const sentenceRenderContent=renderContent;
renderContent=function(){sentenceRenderContent();prepareSentenceLinks()};
function clearSentenceLink(){document.querySelectorAll('.sentence-selected').forEach(el=>el.classList.remove('sentence-selected'));sentenceTip.hidden=true;activeSentence=null}
function positionSentenceTip(){if(!activeSentence||sentenceTip.hidden)return;const nodes=[...activeSentence.group.querySelectorAll('.original .sentence-selected')];const rects=nodes.flatMap(n=>[...n.getClientRects()]);if(!rects.length){sentenceTip.hidden=true;return}const reading=$('#reading').getBoundingClientRect();const rect=rects.find(r=>r.top>=reading.top&&r.bottom<=reading.bottom);if(!rect){sentenceTip.hidden=true;return}sentenceTip.style.maxWidth=Math.min(420,window.innerWidth-28)+'px';sentenceTip.style.left=Math.max(14,Math.min(rect.left,window.innerWidth-sentenceTip.offsetWidth-14))+'px';const above=rect.top-sentenceTip.offsetHeight-12;sentenceTip.style.top=Math.max(8,above>=reading.top?above:rect.bottom+12)+'px';sentenceTip.classList.toggle('tip-below',above<reading.top)}
function activateSentence(clause){const group=clause.closest('.texts'),data=sentenceLinks.get(group);if(!data)return;const side=clause.closest('.original')?'from':'to',id=+clause.dataset.sentenceId,link=data.links.find(l=>l[side].includes(id));if(!link)return;clearSentenceLink();for(const [selector,ids] of [['.original',link.from],['.translated',link.to]])for(const id of ids)group.querySelectorAll(`${selector} [data-sentence-id="${id}"]`).forEach(el=>el.classList.add('sentence-selected'));const text=link.to.map(i=>data.translated[i].text).join('');sentenceTip.replaceChildren();if(link.approximate){const label=document.createElement('small');label.textContent='对应译文参考 · 请结合本段';sentenceTip.append(label)}const p=document.createElement('div');p.textContent=text;sentenceTip.append(p);sentenceTip.hidden=false;activeSentence={group};positionSentenceTip()}
document.addEventListener('click',e=>{if(e.target.closest('.sentence-tip'))return;const entity=e.target.closest('#content [data-person],#content [data-ref-person],#content .entity-place');if(entity){clearSentenceLink();if(entity.matches('.entity-place')&&!entity.dataset.refPlace){e.preventDefault();e.stopImmediatePropagation()}return}const clause=e.target.closest('#content .reading-clause');if(clause&&state.settings.clickLink){if(e.target.closest('[data-person],[data-ref-person],[data-ref-official],[data-ganzhi],[data-inline-note]'))return;if(!window.getSelection()?.isCollapsed)return;e.preventDefault();e.stopImmediatePropagation();activateSentence(clause);return}if(!e.target.closest('.sentence-tip'))clearSentenceLink()},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){clearSentenceLink();clearEntityHighlight()}if((e.key==='Enter'||e.key===' ')&&e.target.matches('#content .entity-place')){if(!e.target.dataset.refPlace){e.preventDefault();e.stopImmediatePropagation()}clearSentenceLink();return}if(e.key==='Enter'&&state.settings.clickLink&&e.target.matches('#content .original,#content .translated')){const clause=e.target.querySelector('.reading-clause');if(clause){e.preventDefault();e.stopImmediatePropagation();activateSentence(clause)}}},true);

function clearEntityHighlight(){++entityPaint;document.querySelectorAll('#content .entity-selected').forEach(el=>el.classList.remove('entity-selected'))}
function referenceHoverIdentity(p,item){if(!p||!item)return null;if(item.link_td_id)return 'ref:'+item.link_td_id;const full=referenceNorm(item.people_xingming||''),short=referenceNorm(item.people_name||'');if(full.length<2||full.length>4||!full.endsWith(short)||!referenceNorm(p.content).includes(full))return null;const ids=new Set((p.ExtRef_Children_people||[]).filter(x=>referenceNorm(x.people_xingming||'')===full&&x.link_td_id).map(x=>x.link_td_id));if(ids.size===1)return 'ref:'+ [...ids][0];if(ids.size>1)return null;return 'context:'+p.tongjian_id+':'+full}
async function highlightReadingEntity(entity){clearEntityHighlight();const stamp=entityPaint;entity.classList.add('entity-selected');if(entity.matches('.entity-place')){const name=toSimple(entity.textContent);document.querySelectorAll('#content .entity-place').forEach(el=>{if(toSimple(el.textContent)===name)el.classList.add('entity-selected')});return}try{const data=await peopleIndex();if(stamp!==entityPaint||!entity.isConnected)return;const identity=el=>{if(el.dataset.refPerson){const r=referenceParts(el.dataset.refPerson);return referenceHoverIdentity(r.p,r.p?.ExtRef_Children_people?.[r.index])}const m=data.occurrences[+el.dataset.person];if(!m)return null;const anchor=data.occurrences[m.contextAnchor]||m;if(anchor.who)return 'local:'+anchor.who;const section=el.closest('.paragraph'),remote=segments[state.segment]?.paragraphs[+section?.dataset.p]?.reference;if(remote)return 'context:'+remote.tongjian_id+':'+anchor.n;return m.contextAnchor!==undefined?'local-context:'+m.c+':'+m.s+':'+m.p+':'+anchor.n:null};const key=identity(entity);if(!key)return;document.querySelectorAll('#content [data-person],#content [data-ref-person]').forEach(el=>{if(identity(el)===key)el.classList.add('entity-selected')})}catch{/* Keep the hovered occurrence highlighted while its profile is unavailable. */}}

function hoverReadingEntity(entity){if(entity===hoveredReadingEntity)return;hoveredReadingEntity=entity;if(entity)highlightReadingEntity(entity);else clearEntityHighlight()}
$('#content').addEventListener('pointerover',e=>{hoverReadingEntity(e.target.closest('[data-person],[data-ref-person],.entity-place'))});
$('#content').addEventListener('pointerout',e=>{const entity=e.target.closest('[data-person],[data-ref-person],.entity-place');if(entity&&entity.contains(e.relatedTarget))return;hoverReadingEntity(e.relatedTarget?.closest?.('#content [data-person],#content [data-ref-person],#content .entity-place')||null)});
$('#content').addEventListener('focusin',e=>hoverReadingEntity(e.target.closest('[data-person],[data-ref-person],.entity-place')));
$('#content').addEventListener('focusout',e=>hoverReadingEntity(e.relatedTarget?.closest?.('#content [data-person],#content [data-ref-person],#content .entity-place')||null));
$('#reading').addEventListener('scroll',positionSentenceTip,{passive:true});window.addEventListener('resize',positionSentenceTip);
applySettings();if(segments[state.segment])renderContent();
