/* Geographic paragraph scenes. Route links are explicit textual movements, not road reconstructions. */
const manualSandboxDialog=sandboxDialog;
let situationMap=null,situationStaticPromise=null;
function situationStatic(){return situationStaticPromise??=Promise.all(['regions','rivers','mountains','routes','passes','cities','places','territory-manifest','paragraph-scenes'].map(async k=>[k,await (await fetch('data/strategic/'+k+'.json')).json()])).then(Object.fromEntries)}
function situationProfilePoint(p){const v=['lat_min','lat_max','lon_min','lon_max'].map(k=>p?.[k]);if(!v.every(Number.isFinite))return null;return [(v[0]+v[1])/2,(v[2]+v[3])/2]}
function situationAliasMatch(names,name){return String(names).split(/[,，、]/).some(x=>referenceNorm(x)===referenceNorm(name))}
function situationMovement(text){const s=referenceNorm(text);if(s.includes('乃率车骑将军邓弘等自河北度至湖'))return [{person:'邓禹、邓弘',from:'河北',to:'湖',quote:'乃率車騎將軍鄧弘等自河北度至湖'},{person:'邓禹',from:'湖',to:'宜陽',quote:'禹以二十四騎脫歸宜陽'},{person:'冯异',from:'湖',to:'回谿阪',quote:'異棄馬奔走，上回谿阪'}];if(s.includes('帝自将征邓奉至堵阳'))return [{person:'帝',from:'堵陽',to:'小長安',quote:'帝追奉至小長安'},{person:'邓奉',from:'堵陽',to:'淯陽',quote:'奉逃歸淯陽'}];if(s.includes('赤眉余众东向宜阳'))return [{person:'赤眉',from:'長安',to:'宜陽',quote:'赤眉餘衆東向宜陽；臣等出長安東都門'}];if(s.includes('自将兵助延围睢阳'))return [{person:'吴汉',from:'廣樂',to:'睢陽',quote:'吳漢留杜茂、陳俊守廣樂，自將兵助延圍睢陽'},{person:'苏茂',from:'廣樂',to:'湖陵',quote:'茂走還湖陵'}];return []}
async function situationDialog(paragraph=state.paragraph||0){
 const segment=segments[state.segment],r=segment?.paragraphs[paragraph];if(!r)return;
 situationMap?.remove();situationMap=null;
 const p=r.reference,places=[...new Map((p?.ExtRef_Children_places||[]).map(x=>[referenceNorm(x.place_name),x])).values()],moves=situationMovement(r.o);
 openDialog('沙盘态势',`<div class="situation-shell"><aside class="situation-reading"><div class="situation-step"><button id="sit-prev" ${paragraph===0?'disabled':''}>上一段</button><strong>第 ${paragraph+1} / ${segment.paragraphs.length} 段</strong><button id="sit-next" ${paragraph===segment.paragraphs.length-1?'disabled':''}>下一段</button></div><h3>${E(segment.title)}</h3><p class="situation-original">${E(r.o)}</p><details><summary>译文</summary><p>${E(r.t||'暂无译文')}</p></details><h4>本段地点</h4><div id="sit-places">正在核对地点…</div><h4>行动依据</h4><div id="sit-evidence"></div><button id="sit-manual">打开手工标绘</button><p class="situation-note">蓝色线路表示史文明确记载的地点间移动，连线为方向示意，不代表实际行军道路。圆圈采用地名资料定位范围的中心，点击可查看范围。</p></aside><section class="situation-map-wrap"><div id="situation-map"></div><div class="situation-top"><label><input id="sit-show" type="checkbox" checked> 态势：</label><button id="sit-points">仅地点</button><button id="sit-routes" class="active">路线</button><span>第 ${paragraph+1} / ${segment.paragraphs.length} 段</span></div><div class="situation-territory"><label><input id="sit-territory" type="checkbox"> 疆域：</label><button id="sit-era-prev">‹</button><span id="sit-era"></span><button id="sit-era-next">›</button></div><div id="sit-minimap" hidden></div><details class="situation-layers" open><summary>图层</summary><p>信息增强</p><label><input data-sit-layer="modern" type="checkbox" checked>现代地名</label><label><input data-sit-layer="hill" type="checkbox" checked>地形增强</label><p>战略要地</p>${[['regions','区块'],['rivers','水路'],['mountains','山脉'],['routes','通道'],['passes','关口'],['cities','城池']].map(([k,n])=>`<label><input data-sit-layer="${k}" type="checkbox" checked>${n}</label>`).join('')}<p>底图</p><label><input type="radio" name="sit-base" value="terrain" checked>地形</label><label><input type="radio" name="sit-base" value="basic">基础</label><label><input type="radio" name="sit-base" value="image">影像</label></details><div class="situation-bottom"><button id="sit-focus">定位本段</button><button id="sit-overview">全国视野</button><button id="sit-eagle">展开鹰眼</button><span id="sit-zoom"></span></div><div id="sit-map-status">正在载入地理图层…</div></section></div>`);
 $('#dialog').classList.add('situation-dialog');const stamp=referenceState.dialogStamp;
 $('#sit-prev').onclick=()=>situationDialog(paragraph-1);$('#sit-next').onclick=()=>situationDialog(paragraph+1);$('#sit-manual').onclick=()=>{situationMap?.remove();situationMap=null;manualSandboxDialog(paragraph)};
 try{
 const data=await situationStatic();if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;
 const importedScene=data['paragraph-scenes'].scenes[p?.tongjian_id];
 const map=situationMap=L.map('situation-map',{zoomControl:false,preferCanvas:true,zoomSnap:.1}).setView([35.3,111.4],5.8);L.control.zoom({position:'topright'}).addTo(map);L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);
 const attribution='地图数据 © OpenStreetMap contributors · 地形 © Esri · 战略地理参考：读通鉴';
 const bases={terrain:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}',{attribution,maxNativeZoom:13,maxZoom:17}),basic:L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution,maxZoom:19}),image:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution,maxZoom:19})};let base=bases.terrain.addTo(map);
 const layers={modern:L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{maxZoom:17,opacity:.8}),hill:L.tileLayer('https://www.dutongjian.com/sandbox/hillshade/hillshade_z15_90m_z8_11/{z}/{x}/{y}.png',{minZoom:5,maxNativeZoom:11,maxZoom:12,opacity:.3})};
 const midpoint=coords=>{let c=coords;while(Array.isArray(c[0]?.[0]))c=c[0];return c[Math.floor(c.length/2)]};
 const colors={regions:'#9362b7',rivers:'#5189e4',mountains:'#343a32',routes:'#c17a31',passes:'#c74141',cities:'#313831'};
 for(const k of ['regions','rivers','mountains','routes','passes','cities']){const group=L.layerGroup();L.geoJSON(data[k],{style:()=>({color:colors[k],weight:k==='routes'?5:2,opacity:.88,fillOpacity:k==='regions'?.035:0,dashArray:k==='rivers'?'8 7':null}),pointToLayer:(f,ll)=>L.marker(ll,{icon:L.divIcon({className:'sit-geopoint '+k,html:k==='cities'?'♜':'×',iconSize:[27,27],iconAnchor:[13,13]})}),onEachFeature:(f,layer)=>{const title=f.properties?.title||'';layer.bindPopup(E(title));if(f.geometry.type==='Point')layer.bindTooltip(E(title),{permanent:true,direction:'bottom',className:'sit-geo-label'});else {const pos=midpoint(f.geometry.coordinates);if(pos&&Number.isFinite(pos[0]))L.marker([pos[1],pos[0]],{interactive:false,icon:L.divIcon({className:'sit-line-label '+k,html:E(title),iconSize:[100,22]})}).addTo(group)}}}).addTo(group);layers[k]=group}
 Object.values(layers).forEach(l=>l.addTo(map));
 const eras=data['territory-manifest'].slice().sort((a,b)=>a.year-b.year);let era=Math.max(0,eras.findLastIndex(x=>x.year<=(p?.year_int||27))),territory=null,eraStamp=0;
 const showEra=async()=>{const ticket=++eraStamp;map.removeLayer(territory||L.layerGroup());territory=null;const item=eras[era];$('#sit-era').textContent=item.name+' · '+(item.year<0?'前'+(-item.year):item.year)+'年';$('#sit-era-prev').disabled=era===0;$('#sit-era-next').disabled=era===eras.length-1;if(!$('#sit-territory').checked)return;try{const geo=await (await fetch('data/strategic/territories/'+item.year+'.json')).json();if(ticket!==eraStamp||stamp!==referenceState.dialogStamp)return;territory=L.geoJSON(geo,{style:f=>({color:f.properties?.stroke||'#7677c9',fillColor:f.properties?.fill||'#aaaaef',fillOpacity:.19,weight:1}),onEachFeature:(f,l)=>l.bindPopup(E(f.properties?.name||f.properties?.NAME||f.properties?.title||item.name))}).addTo(map);territory.bringToBack()}catch{toast('该年份疆域暂不可用')}};
 $('#sit-territory').onchange=showEra;$('#sit-era-prev').onclick=()=>{era--;showEra()};$('#sit-era-next').onclick=()=>{era++;showEra()};showEra();
 let mini=null,miniBounds=null;$('#sit-eagle').onclick=()=>{const el=$('#sit-minimap');el.hidden=!el.hidden;$('#sit-eagle').textContent=el.hidden?'展开鹰眼':'收起鹰眼';if(el.hidden)return;if(!mini){mini=L.map(el,{zoomControl:false,attributionControl:false,dragging:false,scrollWheelZoom:false,doubleClickZoom:false}).setView([35,107],3);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}').addTo(mini);miniBounds=L.rectangle(map.getBounds(),{color:'#287ae6',weight:1,fillOpacity:.15}).addTo(mini);mini.on('click',e=>map.panTo(e.latlng));map.on('moveend',()=>miniBounds.setBounds(map.getBounds()))}mini.invalidateSize()};
 const markerGroup=L.layerGroup().addTo(map),routeGroup=L.layerGroup().addTo(map),allPoints=[];let routeMode=true;
 const profileMap=new Map();for(const [names,profile] of Object.entries(data.places))for(const name of names.split(/[,，]/))profileMap.set(referenceNorm(name),profile);
 const pointMap=new Map();const list=$('#sit-places');list.innerHTML='';
 const updateFocus=()=>{if(importedScene?.map_state?.center){const c=importedScene.map_state.center;map.setView([c[1],c[0]],importedScene.map_state.zoom||5.8);return}if(allPoints.length)map.fitBounds(L.latLngBounds(allPoints).pad(.35),{maxZoom:8.5});else map.setView([35.3,111.4],5.8)};
 const drawRoutes=()=>{routeGroup.clearLayers();const evidence=$('#sit-evidence');evidence.innerHTML='';for(const m of moves){const a=pointMap.get(referenceNorm(m.from)),b=pointMap.get(referenceNorm(m.to));const item=document.createElement('p');item.textContent=m.person+'：'+m.from+' → '+m.to+'。依据：'+m.quote+(a&&b?'':'（地点定位待补齐）');evidence.append(item);if(!a||!b)continue;const line=L.polyline([a,b],{color:'#2961e8',weight:3,opacity:.95}).bindTooltip(E(m.person+'：'+m.quote)).addTo(routeGroup);[a,b].forEach((ll,i)=>L.marker(ll,{icon:L.divIcon({className:'sit-route-node',html:`<span>${i+1}</span><b>${E(m.person)}</b>`,iconSize:[26,26],iconAnchor:[13,13]})}).addTo(routeGroup));const mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];const angle=()=>{const aa=map.latLngToLayerPoint(a),bb=map.latLngToLayerPoint(b);return Math.atan2(bb.y-aa.y,bb.x-aa.x)*180/Math.PI};const icon=()=>L.divIcon({className:'sit-route-arrow',html:`<span style="transform:rotate(${angle()}deg)">➤</span>`,iconSize:[24,24],iconAnchor:[12,12]});const arrow=L.marker(mid,{icon:icon(),interactive:false}).addTo(routeGroup);map.on('zoomend',()=>{if(map.hasLayer(arrow))arrow.setIcon(icon())})}if(!moves.length)evidence.innerHTML='<p>本段暂无已核对的移动路线，显示地点信息。</p>';if(!routeMode||!$('#sit-show').checked)map.removeLayer(routeGroup)};
 let importedStatus='';const statuses=[];
 if(importedScene){importedStatus=drawImportedScene(importedScene,map,markerGroup,routeGroup,allPoints)}else{
 const names=[...new Set([...places.map(x=>x.place_name),...moves.flatMap(x=>[x.from,x.to])])];
 await Promise.all(names.map(async name=>{let profile=profileMap.get(referenceNorm(name));const mention=places.find(x=>referenceNorm(x.place_name)===referenceNorm(name));if(!profile&&mention){try{profile=(await referenceAPI('resolved_place_info',{place_tongjian_id:mention.tongjian_id,page:1,page_size:1})).resolved_profile}catch{}}
 if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;
 let ll=situationProfilePoint(profile);if(!ll){const f=data.cities.features.find(x=>situationAliasMatch(x.properties.title.replace(/[（()）]/g,','),name));if(f)ll=[f.geometry.coordinates[1],f.geometry.coordinates[0]]}
 const button=document.createElement('button');button.textContent=name+(ll?'':' · 暂无定位');button.disabled=!ll;list.append(button);if(!ll){statuses.push(name);return}allPoints.push(ll);pointMap.set(referenceNorm(name),ll);const marker=L.circleMarker(ll,{radius:9,color:'#295dec',weight:2,fillColor:'#191d27',fillOpacity:1}).addTo(markerGroup).bindTooltip(E(name),{permanent:true,direction:'right',className:'sit-place-label'});const popup=`<b>${E(name)}</b><p>${E(profile?.intro||'战略地理参考地点')}</p><p>${E(profile?.modern_location||'')}</p><small>定位${profile?'采用资料范围中心，非精确遗址点':'采用战略地理图层'}</small>`;marker.bindPopup(popup);if(profile){const bounds=[[profile.lat_min,profile.lon_min],[profile.lat_max,profile.lon_max]];marker.on('click',()=>{const box=L.rectangle(bounds,{color:'#e9b835',weight:1,fillOpacity:.08}).addTo(map);box.once('click',()=>map.removeLayer(box));marker.once('popupclose',()=>map.removeLayer(box))})}button.onclick=()=>{map.setView(ll,9);marker.openPopup()};
 }));if(stamp!==referenceState.dialogStamp||!$('#dialog').open)return;drawRoutes();}
 map.invalidateSize();updateFocus();$('#sit-map-status').textContent=importedStatus|| (statuses.length?'未定位：'+statuses.join('、'):'已载入本段地点与六类战略图层');
 const toggle=()=>{for(const l of [markerGroup,routeGroup])map.removeLayer(l);if($('#sit-show').checked){markerGroup.addTo(map);if(routeMode)routeGroup.addTo(map)}$('#sit-points').classList.toggle('active',!routeMode);$('#sit-routes').classList.toggle('active',routeMode)};$('#sit-show').onchange=toggle;$('#sit-points').onclick=()=>{routeMode=false;toggle()};$('#sit-routes').onclick=()=>{routeMode=true;toggle()};
 document.querySelectorAll('[data-sit-layer]').forEach(input=>input.onchange=()=>input.checked?layers[input.dataset.sitLayer].addTo(map):map.removeLayer(layers[input.dataset.sitLayer]));document.querySelectorAll('[name="sit-base"]').forEach(input=>input.onchange=()=>{map.removeLayer(base);base=bases[input.value].addTo(map);base.bringToBack()});$('#sit-focus').onclick=updateFocus;$('#sit-overview').onclick=()=>map.setView([35.3,106.8],4);const zoom=()=>$('#sit-zoom')&&($('#sit-zoom').textContent='Zoom '+map.getZoom().toFixed(2));map.on('zoomend',zoom);zoom();
 }catch(error){if(stamp===referenceState.dialogStamp)$('#sit-map-status').textContent='地图未能载入：'+error.message}
}
sandboxDialog=situationDialog;actions.sandbox=()=>situationDialog();sandboxToolButton.textContent='沙盘态势';
const situationOpenDialog=openDialog;openDialog=function(title,html){$('#dialog').classList.remove('situation-dialog');return situationOpenDialog(title,html)};
$('#dialog').addEventListener('close',()=>{situationMap?.remove();situationMap=null});
